"""Contains all the data models used in inputs/outputs"""

from .add_users_to_internal_squad_response_dto import AddUsersToInternalSquadResponseDto
from .add_users_to_internal_squad_response_dto_response import AddUsersToInternalSquadResponseDtoResponse
from .api_tokens_controller_create_response_500 import ApiTokensControllerCreateResponse500
from .api_tokens_controller_delete_response_500 import ApiTokensControllerDeleteResponse500
from .api_tokens_controller_find_all_response_500 import ApiTokensControllerFindAllResponse500
from .auth_controller_get_status_response_500 import AuthControllerGetStatusResponse500
from .auth_controller_login_response_401 import AuthControllerLoginResponse401
from .auth_controller_login_response_500 import AuthControllerLoginResponse500
from .auth_controller_oauth_2_authorize_response_500 import AuthControllerOauth2AuthorizeResponse500
from .auth_controller_oauth_2_callback_response_500 import AuthControllerOauth2CallbackResponse500
from .auth_controller_register_response_403 import AuthControllerRegisterResponse403
from .auth_controller_register_response_500 import AuthControllerRegisterResponse500
from .auth_controller_telegram_callback_response_500 import AuthControllerTelegramCallbackResponse500
from .bulk_all_reset_traffic_users_response_dto import BulkAllResetTrafficUsersResponseDto
from .bulk_all_reset_traffic_users_response_dto_response import BulkAllResetTrafficUsersResponseDtoResponse
from .bulk_all_update_users_request_dto import BulkAllUpdateUsersRequestDto
from .bulk_all_update_users_request_dto_status import BulkAllUpdateUsersRequestDtoStatus
from .bulk_all_update_users_request_dto_traffic_limit_strategy import BulkAllUpdateUsersRequestDtoTrafficLimitStrategy
from .bulk_all_update_users_response_dto import BulkAllUpdateUsersResponseDto
from .bulk_all_update_users_response_dto_response import BulkAllUpdateUsersResponseDtoResponse
from .bulk_delete_hosts_request_dto import BulkDeleteHostsRequestDto
from .bulk_delete_hosts_response_dto import BulkDeleteHostsResponseDto
from .bulk_delete_hosts_response_dto_response_item import BulkDeleteHostsResponseDtoResponseItem
from .bulk_delete_hosts_response_dto_response_item_inbound import BulkDeleteHostsResponseDtoResponseItemInbound
from .bulk_delete_hosts_response_dto_response_item_security_layer import (
    BulkDeleteHostsResponseDtoResponseItemSecurityLayer,
)
from .bulk_delete_users_by_status_request_dto import BulkDeleteUsersByStatusRequestDto
from .bulk_delete_users_by_status_request_dto_status import BulkDeleteUsersByStatusRequestDtoStatus
from .bulk_delete_users_by_status_response_dto import BulkDeleteUsersByStatusResponseDto
from .bulk_delete_users_by_status_response_dto_response import BulkDeleteUsersByStatusResponseDtoResponse
from .bulk_delete_users_request_dto import BulkDeleteUsersRequestDto
from .bulk_delete_users_response_dto import BulkDeleteUsersResponseDto
from .bulk_delete_users_response_dto_response import BulkDeleteUsersResponseDtoResponse
from .bulk_disable_hosts_request_dto import BulkDisableHostsRequestDto
from .bulk_disable_hosts_response_dto import BulkDisableHostsResponseDto
from .bulk_disable_hosts_response_dto_response_item import BulkDisableHostsResponseDtoResponseItem
from .bulk_disable_hosts_response_dto_response_item_inbound import BulkDisableHostsResponseDtoResponseItemInbound
from .bulk_disable_hosts_response_dto_response_item_security_layer import (
    BulkDisableHostsResponseDtoResponseItemSecurityLayer,
)
from .bulk_enable_hosts_request_dto import BulkEnableHostsRequestDto
from .bulk_enable_hosts_response_dto import BulkEnableHostsResponseDto
from .bulk_enable_hosts_response_dto_response_item import BulkEnableHostsResponseDtoResponseItem
from .bulk_enable_hosts_response_dto_response_item_inbound import BulkEnableHostsResponseDtoResponseItemInbound
from .bulk_enable_hosts_response_dto_response_item_security_layer import (
    BulkEnableHostsResponseDtoResponseItemSecurityLayer,
)
from .bulk_reset_traffic_users_request_dto import BulkResetTrafficUsersRequestDto
from .bulk_reset_traffic_users_response_dto import BulkResetTrafficUsersResponseDto
from .bulk_reset_traffic_users_response_dto_response import BulkResetTrafficUsersResponseDtoResponse
from .bulk_revoke_users_subscription_request_dto import BulkRevokeUsersSubscriptionRequestDto
from .bulk_revoke_users_subscription_response_dto import BulkRevokeUsersSubscriptionResponseDto
from .bulk_revoke_users_subscription_response_dto_response import BulkRevokeUsersSubscriptionResponseDtoResponse
from .bulk_update_users_request_dto import BulkUpdateUsersRequestDto
from .bulk_update_users_request_dto_fields import BulkUpdateUsersRequestDtoFields
from .bulk_update_users_request_dto_fields_status import BulkUpdateUsersRequestDtoFieldsStatus
from .bulk_update_users_request_dto_fields_traffic_limit_strategy import (
    BulkUpdateUsersRequestDtoFieldsTrafficLimitStrategy,
)
from .bulk_update_users_response_dto import BulkUpdateUsersResponseDto
from .bulk_update_users_response_dto_response import BulkUpdateUsersResponseDtoResponse
from .bulk_update_users_squads_request_dto import BulkUpdateUsersSquadsRequestDto
from .bulk_update_users_squads_response_dto import BulkUpdateUsersSquadsResponseDto
from .bulk_update_users_squads_response_dto_response import BulkUpdateUsersSquadsResponseDtoResponse
from .config_profile_controller_create_config_profile_response_500 import (
    ConfigProfileControllerCreateConfigProfileResponse500,
)
from .config_profile_controller_delete_config_profile_by_uuid_response_500 import (
    ConfigProfileControllerDeleteConfigProfileByUuidResponse500,
)
from .config_profile_controller_get_all_inbounds_response_500 import ConfigProfileControllerGetAllInboundsResponse500
from .config_profile_controller_get_config_profile_by_uuid_response_500 import (
    ConfigProfileControllerGetConfigProfileByUuidResponse500,
)
from .config_profile_controller_get_config_profiles_response_500 import (
    ConfigProfileControllerGetConfigProfilesResponse500,
)
from .config_profile_controller_get_inbounds_by_profile_uuid_response_500 import (
    ConfigProfileControllerGetInboundsByProfileUuidResponse500,
)
from .config_profile_controller_update_config_profile_response_500 import (
    ConfigProfileControllerUpdateConfigProfileResponse500,
)
from .create_api_token_request_dto import CreateApiTokenRequestDto
from .create_api_token_response_dto import CreateApiTokenResponseDto
from .create_api_token_response_dto_response import CreateApiTokenResponseDtoResponse
from .create_config_profile_request_dto import CreateConfigProfileRequestDto
from .create_config_profile_request_dto_config import CreateConfigProfileRequestDtoConfig
from .create_config_profile_response_dto import CreateConfigProfileResponseDto
from .create_config_profile_response_dto_response import CreateConfigProfileResponseDtoResponse
from .create_config_profile_response_dto_response_inbounds_item import (
    CreateConfigProfileResponseDtoResponseInboundsItem,
)
from .create_config_profile_response_dto_response_nodes_item import CreateConfigProfileResponseDtoResponseNodesItem
from .create_host_request_dto import CreateHostRequestDto
from .create_host_request_dto_alpn import CreateHostRequestDtoAlpn
from .create_host_request_dto_fingerprint import CreateHostRequestDtoFingerprint
from .create_host_request_dto_inbound import CreateHostRequestDtoInbound
from .create_host_request_dto_security_layer import CreateHostRequestDtoSecurityLayer
from .create_host_response_dto import CreateHostResponseDto
from .create_host_response_dto_response import CreateHostResponseDtoResponse
from .create_host_response_dto_response_inbound import CreateHostResponseDtoResponseInbound
from .create_host_response_dto_response_security_layer import CreateHostResponseDtoResponseSecurityLayer
from .create_infra_billing_history_record_request_dto import CreateInfraBillingHistoryRecordRequestDto
from .create_infra_billing_history_record_response_dto import CreateInfraBillingHistoryRecordResponseDto
from .create_infra_billing_history_record_response_dto_response import (
    CreateInfraBillingHistoryRecordResponseDtoResponse,
)
from .create_infra_billing_history_record_response_dto_response_records_item import (
    CreateInfraBillingHistoryRecordResponseDtoResponseRecordsItem,
)
from .create_infra_billing_history_record_response_dto_response_records_item_provider import (
    CreateInfraBillingHistoryRecordResponseDtoResponseRecordsItemProvider,
)
from .create_infra_billing_node_request_dto import CreateInfraBillingNodeRequestDto
from .create_infra_billing_node_response_dto import CreateInfraBillingNodeResponseDto
from .create_infra_billing_node_response_dto_response import CreateInfraBillingNodeResponseDtoResponse
from .create_infra_billing_node_response_dto_response_available_billing_nodes_item import (
    CreateInfraBillingNodeResponseDtoResponseAvailableBillingNodesItem,
)
from .create_infra_billing_node_response_dto_response_billing_nodes_item import (
    CreateInfraBillingNodeResponseDtoResponseBillingNodesItem,
)
from .create_infra_billing_node_response_dto_response_billing_nodes_item_node import (
    CreateInfraBillingNodeResponseDtoResponseBillingNodesItemNode,
)
from .create_infra_billing_node_response_dto_response_billing_nodes_item_provider import (
    CreateInfraBillingNodeResponseDtoResponseBillingNodesItemProvider,
)
from .create_infra_billing_node_response_dto_response_stats import CreateInfraBillingNodeResponseDtoResponseStats
from .create_infra_provider_request_dto import CreateInfraProviderRequestDto
from .create_infra_provider_response_dto import CreateInfraProviderResponseDto
from .create_infra_provider_response_dto_response import CreateInfraProviderResponseDtoResponse
from .create_infra_provider_response_dto_response_billing_history import (
    CreateInfraProviderResponseDtoResponseBillingHistory,
)
from .create_infra_provider_response_dto_response_billing_nodes_item import (
    CreateInfraProviderResponseDtoResponseBillingNodesItem,
)
from .create_internal_squad_request_dto import CreateInternalSquadRequestDto
from .create_internal_squad_response_dto import CreateInternalSquadResponseDto
from .create_internal_squad_response_dto_response import CreateInternalSquadResponseDtoResponse
from .create_internal_squad_response_dto_response_inbounds_item import (
    CreateInternalSquadResponseDtoResponseInboundsItem,
)
from .create_internal_squad_response_dto_response_info import CreateInternalSquadResponseDtoResponseInfo
from .create_node_request_dto import CreateNodeRequestDto
from .create_node_request_dto_config_profile import CreateNodeRequestDtoConfigProfile
from .create_node_response_dto import CreateNodeResponseDto
from .create_node_response_dto_response import CreateNodeResponseDtoResponse
from .create_node_response_dto_response_config_profile import CreateNodeResponseDtoResponseConfigProfile
from .create_node_response_dto_response_config_profile_active_inbounds_item import (
    CreateNodeResponseDtoResponseConfigProfileActiveInboundsItem,
)
from .create_node_response_dto_response_provider_type_0 import CreateNodeResponseDtoResponseProviderType0
from .create_user_hwid_device_request_dto import CreateUserHwidDeviceRequestDto
from .create_user_hwid_device_response_dto import CreateUserHwidDeviceResponseDto
from .create_user_hwid_device_response_dto_response import CreateUserHwidDeviceResponseDtoResponse
from .create_user_hwid_device_response_dto_response_devices_item import (
    CreateUserHwidDeviceResponseDtoResponseDevicesItem,
)
from .create_user_request_dto import CreateUserRequestDto
from .create_user_request_dto_status import CreateUserRequestDtoStatus
from .create_user_request_dto_traffic_limit_strategy import CreateUserRequestDtoTrafficLimitStrategy
from .create_user_response_dto import CreateUserResponseDto
from .create_user_response_dto_response import CreateUserResponseDtoResponse
from .create_user_response_dto_response_active_internal_squads_item import (
    CreateUserResponseDtoResponseActiveInternalSquadsItem,
)
from .create_user_response_dto_response_happ import CreateUserResponseDtoResponseHapp
from .create_user_response_dto_response_last_connected_node_type_0 import (
    CreateUserResponseDtoResponseLastConnectedNodeType0,
)
from .create_user_response_dto_response_status import CreateUserResponseDtoResponseStatus
from .create_user_response_dto_response_traffic_limit_strategy import CreateUserResponseDtoResponseTrafficLimitStrategy
from .delete_api_token_response_dto import DeleteApiTokenResponseDto
from .delete_config_profile_response_dto import DeleteConfigProfileResponseDto
from .delete_config_profile_response_dto_response import DeleteConfigProfileResponseDtoResponse
from .delete_host_response_dto import DeleteHostResponseDto
from .delete_host_response_dto_response import DeleteHostResponseDtoResponse
from .delete_infra_billing_history_record_by_uuid_response_dto import DeleteInfraBillingHistoryRecordByUuidResponseDto
from .delete_infra_billing_history_record_by_uuid_response_dto_response import (
    DeleteInfraBillingHistoryRecordByUuidResponseDtoResponse,
)
from .delete_infra_billing_history_record_by_uuid_response_dto_response_records_item import (
    DeleteInfraBillingHistoryRecordByUuidResponseDtoResponseRecordsItem,
)
from .delete_infra_billing_history_record_by_uuid_response_dto_response_records_item_provider import (
    DeleteInfraBillingHistoryRecordByUuidResponseDtoResponseRecordsItemProvider,
)
from .delete_infra_billing_node_by_uuid_response_dto import DeleteInfraBillingNodeByUuidResponseDto
from .delete_infra_billing_node_by_uuid_response_dto_response import DeleteInfraBillingNodeByUuidResponseDtoResponse
from .delete_infra_billing_node_by_uuid_response_dto_response_available_billing_nodes_item import (
    DeleteInfraBillingNodeByUuidResponseDtoResponseAvailableBillingNodesItem,
)
from .delete_infra_billing_node_by_uuid_response_dto_response_billing_nodes_item import (
    DeleteInfraBillingNodeByUuidResponseDtoResponseBillingNodesItem,
)
from .delete_infra_billing_node_by_uuid_response_dto_response_billing_nodes_item_node import (
    DeleteInfraBillingNodeByUuidResponseDtoResponseBillingNodesItemNode,
)
from .delete_infra_billing_node_by_uuid_response_dto_response_billing_nodes_item_provider import (
    DeleteInfraBillingNodeByUuidResponseDtoResponseBillingNodesItemProvider,
)
from .delete_infra_billing_node_by_uuid_response_dto_response_stats import (
    DeleteInfraBillingNodeByUuidResponseDtoResponseStats,
)
from .delete_infra_provider_by_uuid_response_dto import DeleteInfraProviderByUuidResponseDto
from .delete_infra_provider_by_uuid_response_dto_response import DeleteInfraProviderByUuidResponseDtoResponse
from .delete_internal_squad_response_dto import DeleteInternalSquadResponseDto
from .delete_internal_squad_response_dto_response import DeleteInternalSquadResponseDtoResponse
from .delete_node_response_dto import DeleteNodeResponseDto
from .delete_node_response_dto_response import DeleteNodeResponseDtoResponse
from .delete_user_hwid_device_request_dto import DeleteUserHwidDeviceRequestDto
from .delete_user_hwid_device_response_dto import DeleteUserHwidDeviceResponseDto
from .delete_user_hwid_device_response_dto_response import DeleteUserHwidDeviceResponseDtoResponse
from .delete_user_hwid_device_response_dto_response_devices_item import (
    DeleteUserHwidDeviceResponseDtoResponseDevicesItem,
)
from .delete_user_response_dto import DeleteUserResponseDto
from .delete_user_response_dto_response import DeleteUserResponseDtoResponse
from .disable_node_response_dto import DisableNodeResponseDto
from .disable_node_response_dto_response import DisableNodeResponseDtoResponse
from .disable_node_response_dto_response_config_profile import DisableNodeResponseDtoResponseConfigProfile
from .disable_node_response_dto_response_config_profile_active_inbounds_item import (
    DisableNodeResponseDtoResponseConfigProfileActiveInboundsItem,
)
from .disable_node_response_dto_response_provider_type_0 import DisableNodeResponseDtoResponseProviderType0
from .disable_user_response_dto import DisableUserResponseDto
from .disable_user_response_dto_response import DisableUserResponseDtoResponse
from .disable_user_response_dto_response_active_internal_squads_item import (
    DisableUserResponseDtoResponseActiveInternalSquadsItem,
)
from .disable_user_response_dto_response_happ import DisableUserResponseDtoResponseHapp
from .disable_user_response_dto_response_last_connected_node_type_0 import (
    DisableUserResponseDtoResponseLastConnectedNodeType0,
)
from .disable_user_response_dto_response_status import DisableUserResponseDtoResponseStatus
from .disable_user_response_dto_response_traffic_limit_strategy import (
    DisableUserResponseDtoResponseTrafficLimitStrategy,
)
from .enable_node_response_dto import EnableNodeResponseDto
from .enable_node_response_dto_response import EnableNodeResponseDtoResponse
from .enable_node_response_dto_response_config_profile import EnableNodeResponseDtoResponseConfigProfile
from .enable_node_response_dto_response_config_profile_active_inbounds_item import (
    EnableNodeResponseDtoResponseConfigProfileActiveInboundsItem,
)
from .enable_node_response_dto_response_provider_type_0 import EnableNodeResponseDtoResponseProviderType0
from .enable_user_response_dto import EnableUserResponseDto
from .enable_user_response_dto_response import EnableUserResponseDtoResponse
from .enable_user_response_dto_response_active_internal_squads_item import (
    EnableUserResponseDtoResponseActiveInternalSquadsItem,
)
from .enable_user_response_dto_response_happ import EnableUserResponseDtoResponseHapp
from .enable_user_response_dto_response_last_connected_node_type_0 import (
    EnableUserResponseDtoResponseLastConnectedNodeType0,
)
from .enable_user_response_dto_response_status import EnableUserResponseDtoResponseStatus
from .enable_user_response_dto_response_traffic_limit_strategy import EnableUserResponseDtoResponseTrafficLimitStrategy
from .find_all_api_tokens_response_dto import FindAllApiTokensResponseDto
from .find_all_api_tokens_response_dto_response import FindAllApiTokensResponseDtoResponse
from .find_all_api_tokens_response_dto_response_api_keys_item import FindAllApiTokensResponseDtoResponseApiKeysItem
from .find_all_api_tokens_response_dto_response_docs import FindAllApiTokensResponseDtoResponseDocs
from .get_all_host_tags_response_dto import GetAllHostTagsResponseDto
from .get_all_host_tags_response_dto_response import GetAllHostTagsResponseDtoResponse
from .get_all_hosts_response_dto import GetAllHostsResponseDto
from .get_all_hosts_response_dto_response_item import GetAllHostsResponseDtoResponseItem
from .get_all_hosts_response_dto_response_item_inbound import GetAllHostsResponseDtoResponseItemInbound
from .get_all_hosts_response_dto_response_item_security_layer import GetAllHostsResponseDtoResponseItemSecurityLayer
from .get_all_inbounds_response_dto import GetAllInboundsResponseDto
from .get_all_inbounds_response_dto_response import GetAllInboundsResponseDtoResponse
from .get_all_inbounds_response_dto_response_inbounds_item import GetAllInboundsResponseDtoResponseInboundsItem
from .get_all_nodes_response_dto import GetAllNodesResponseDto
from .get_all_nodes_response_dto_response_item import GetAllNodesResponseDtoResponseItem
from .get_all_nodes_response_dto_response_item_config_profile import GetAllNodesResponseDtoResponseItemConfigProfile
from .get_all_nodes_response_dto_response_item_config_profile_active_inbounds_item import (
    GetAllNodesResponseDtoResponseItemConfigProfileActiveInboundsItem,
)
from .get_all_nodes_response_dto_response_item_provider_type_0 import GetAllNodesResponseDtoResponseItemProviderType0
from .get_all_subscriptions_response_dto import GetAllSubscriptionsResponseDto
from .get_all_subscriptions_response_dto_response import GetAllSubscriptionsResponseDtoResponse
from .get_all_subscriptions_response_dto_response_subscriptions_item import (
    GetAllSubscriptionsResponseDtoResponseSubscriptionsItem,
)
from .get_all_subscriptions_response_dto_response_subscriptions_item_ss_conf_links import (
    GetAllSubscriptionsResponseDtoResponseSubscriptionsItemSsConfLinks,
)
from .get_all_subscriptions_response_dto_response_subscriptions_item_user import (
    GetAllSubscriptionsResponseDtoResponseSubscriptionsItemUser,
)
from .get_all_subscriptions_response_dto_response_subscriptions_item_user_traffic_limit_strategy import (
    GetAllSubscriptionsResponseDtoResponseSubscriptionsItemUserTrafficLimitStrategy,
)
from .get_all_subscriptions_response_dto_response_subscriptions_item_user_user_status import (
    GetAllSubscriptionsResponseDtoResponseSubscriptionsItemUserUserStatus,
)
from .get_all_tags_response_dto import GetAllTagsResponseDto
from .get_all_tags_response_dto_response import GetAllTagsResponseDtoResponse
from .get_all_users_response_dto import GetAllUsersResponseDto
from .get_all_users_response_dto_response import GetAllUsersResponseDtoResponse
from .get_all_users_response_dto_response_users_item import GetAllUsersResponseDtoResponseUsersItem
from .get_all_users_response_dto_response_users_item_active_internal_squads_item import (
    GetAllUsersResponseDtoResponseUsersItemActiveInternalSquadsItem,
)
from .get_all_users_response_dto_response_users_item_happ import GetAllUsersResponseDtoResponseUsersItemHapp
from .get_all_users_response_dto_response_users_item_last_connected_node_type_0 import (
    GetAllUsersResponseDtoResponseUsersItemLastConnectedNodeType0,
)
from .get_all_users_response_dto_response_users_item_status import GetAllUsersResponseDtoResponseUsersItemStatus
from .get_all_users_response_dto_response_users_item_traffic_limit_strategy import (
    GetAllUsersResponseDtoResponseUsersItemTrafficLimitStrategy,
)
from .get_bandwidth_stats_response_dto import GetBandwidthStatsResponseDto
from .get_bandwidth_stats_response_dto_response import GetBandwidthStatsResponseDtoResponse
from .get_bandwidth_stats_response_dto_response_bandwidth_calendar_month import (
    GetBandwidthStatsResponseDtoResponseBandwidthCalendarMonth,
)
from .get_bandwidth_stats_response_dto_response_bandwidth_current_year import (
    GetBandwidthStatsResponseDtoResponseBandwidthCurrentYear,
)
from .get_bandwidth_stats_response_dto_response_bandwidth_last_30_days import (
    GetBandwidthStatsResponseDtoResponseBandwidthLast30Days,
)
from .get_bandwidth_stats_response_dto_response_bandwidth_last_seven_days import (
    GetBandwidthStatsResponseDtoResponseBandwidthLastSevenDays,
)
from .get_bandwidth_stats_response_dto_response_bandwidth_last_two_days import (
    GetBandwidthStatsResponseDtoResponseBandwidthLastTwoDays,
)
from .get_config_profile_by_uuid_response_dto import GetConfigProfileByUuidResponseDto
from .get_config_profile_by_uuid_response_dto_response import GetConfigProfileByUuidResponseDtoResponse
from .get_config_profile_by_uuid_response_dto_response_inbounds_item import (
    GetConfigProfileByUuidResponseDtoResponseInboundsItem,
)
from .get_config_profile_by_uuid_response_dto_response_nodes_item import (
    GetConfigProfileByUuidResponseDtoResponseNodesItem,
)
from .get_config_profiles_response_dto import GetConfigProfilesResponseDto
from .get_config_profiles_response_dto_response import GetConfigProfilesResponseDtoResponse
from .get_config_profiles_response_dto_response_config_profiles_item import (
    GetConfigProfilesResponseDtoResponseConfigProfilesItem,
)
from .get_config_profiles_response_dto_response_config_profiles_item_inbounds_item import (
    GetConfigProfilesResponseDtoResponseConfigProfilesItemInboundsItem,
)
from .get_config_profiles_response_dto_response_config_profiles_item_nodes_item import (
    GetConfigProfilesResponseDtoResponseConfigProfilesItemNodesItem,
)
from .get_inbounds_by_profile_uuid_response_dto import GetInboundsByProfileUuidResponseDto
from .get_inbounds_by_profile_uuid_response_dto_response import GetInboundsByProfileUuidResponseDtoResponse
from .get_inbounds_by_profile_uuid_response_dto_response_inbounds_item import (
    GetInboundsByProfileUuidResponseDtoResponseInboundsItem,
)
from .get_infra_billing_history_records_response_dto import GetInfraBillingHistoryRecordsResponseDto
from .get_infra_billing_history_records_response_dto_response import GetInfraBillingHistoryRecordsResponseDtoResponse
from .get_infra_billing_history_records_response_dto_response_records_item import (
    GetInfraBillingHistoryRecordsResponseDtoResponseRecordsItem,
)
from .get_infra_billing_history_records_response_dto_response_records_item_provider import (
    GetInfraBillingHistoryRecordsResponseDtoResponseRecordsItemProvider,
)
from .get_infra_billing_nodes_response_dto import GetInfraBillingNodesResponseDto
from .get_infra_billing_nodes_response_dto_response import GetInfraBillingNodesResponseDtoResponse
from .get_infra_billing_nodes_response_dto_response_available_billing_nodes_item import (
    GetInfraBillingNodesResponseDtoResponseAvailableBillingNodesItem,
)
from .get_infra_billing_nodes_response_dto_response_billing_nodes_item import (
    GetInfraBillingNodesResponseDtoResponseBillingNodesItem,
)
from .get_infra_billing_nodes_response_dto_response_billing_nodes_item_node import (
    GetInfraBillingNodesResponseDtoResponseBillingNodesItemNode,
)
from .get_infra_billing_nodes_response_dto_response_billing_nodes_item_provider import (
    GetInfraBillingNodesResponseDtoResponseBillingNodesItemProvider,
)
from .get_infra_billing_nodes_response_dto_response_stats import GetInfraBillingNodesResponseDtoResponseStats
from .get_infra_provider_by_uuid_response_dto import GetInfraProviderByUuidResponseDto
from .get_infra_provider_by_uuid_response_dto_response import GetInfraProviderByUuidResponseDtoResponse
from .get_infra_provider_by_uuid_response_dto_response_billing_history import (
    GetInfraProviderByUuidResponseDtoResponseBillingHistory,
)
from .get_infra_provider_by_uuid_response_dto_response_billing_nodes_item import (
    GetInfraProviderByUuidResponseDtoResponseBillingNodesItem,
)
from .get_infra_providers_response_dto import GetInfraProvidersResponseDto
from .get_infra_providers_response_dto_response import GetInfraProvidersResponseDtoResponse
from .get_infra_providers_response_dto_response_providers_item import GetInfraProvidersResponseDtoResponseProvidersItem
from .get_infra_providers_response_dto_response_providers_item_billing_history import (
    GetInfraProvidersResponseDtoResponseProvidersItemBillingHistory,
)
from .get_infra_providers_response_dto_response_providers_item_billing_nodes_item import (
    GetInfraProvidersResponseDtoResponseProvidersItemBillingNodesItem,
)
from .get_internal_squad_accessible_nodes_response_dto import GetInternalSquadAccessibleNodesResponseDto
from .get_internal_squad_accessible_nodes_response_dto_response import (
    GetInternalSquadAccessibleNodesResponseDtoResponse,
)
from .get_internal_squad_accessible_nodes_response_dto_response_accessible_nodes_item import (
    GetInternalSquadAccessibleNodesResponseDtoResponseAccessibleNodesItem,
)
from .get_internal_squad_by_uuid_response_dto import GetInternalSquadByUuidResponseDto
from .get_internal_squad_by_uuid_response_dto_response import GetInternalSquadByUuidResponseDtoResponse
from .get_internal_squad_by_uuid_response_dto_response_inbounds_item import (
    GetInternalSquadByUuidResponseDtoResponseInboundsItem,
)
from .get_internal_squad_by_uuid_response_dto_response_info import GetInternalSquadByUuidResponseDtoResponseInfo
from .get_internal_squads_response_dto import GetInternalSquadsResponseDto
from .get_internal_squads_response_dto_response import GetInternalSquadsResponseDtoResponse
from .get_internal_squads_response_dto_response_internal_squads_item import (
    GetInternalSquadsResponseDtoResponseInternalSquadsItem,
)
from .get_internal_squads_response_dto_response_internal_squads_item_inbounds_item import (
    GetInternalSquadsResponseDtoResponseInternalSquadsItemInboundsItem,
)
from .get_internal_squads_response_dto_response_internal_squads_item_info import (
    GetInternalSquadsResponseDtoResponseInternalSquadsItemInfo,
)
from .get_node_user_usage_by_range_response_dto import GetNodeUserUsageByRangeResponseDto
from .get_node_user_usage_by_range_response_dto_response_item import GetNodeUserUsageByRangeResponseDtoResponseItem
from .get_nodes_metrics_response_dto import GetNodesMetricsResponseDto
from .get_nodes_metrics_response_dto_response import GetNodesMetricsResponseDtoResponse
from .get_nodes_metrics_response_dto_response_nodes_item import GetNodesMetricsResponseDtoResponseNodesItem
from .get_nodes_metrics_response_dto_response_nodes_item_inbounds_stats_item import (
    GetNodesMetricsResponseDtoResponseNodesItemInboundsStatsItem,
)
from .get_nodes_metrics_response_dto_response_nodes_item_outbounds_stats_item import (
    GetNodesMetricsResponseDtoResponseNodesItemOutboundsStatsItem,
)
from .get_nodes_realtime_usage_response_dto import GetNodesRealtimeUsageResponseDto
from .get_nodes_realtime_usage_response_dto_response_item import GetNodesRealtimeUsageResponseDtoResponseItem
from .get_nodes_statistics_response_dto import GetNodesStatisticsResponseDto
from .get_nodes_statistics_response_dto_response import GetNodesStatisticsResponseDtoResponse
from .get_nodes_statistics_response_dto_response_last_seven_days_item import (
    GetNodesStatisticsResponseDtoResponseLastSevenDaysItem,
)
from .get_nodes_usage_by_range_response_dto import GetNodesUsageByRangeResponseDto
from .get_nodes_usage_by_range_response_dto_response_item import GetNodesUsageByRangeResponseDtoResponseItem
from .get_one_host_response_dto import GetOneHostResponseDto
from .get_one_host_response_dto_response import GetOneHostResponseDtoResponse
from .get_one_host_response_dto_response_inbound import GetOneHostResponseDtoResponseInbound
from .get_one_host_response_dto_response_security_layer import GetOneHostResponseDtoResponseSecurityLayer
from .get_one_node_response_dto import GetOneNodeResponseDto
from .get_one_node_response_dto_response import GetOneNodeResponseDtoResponse
from .get_one_node_response_dto_response_config_profile import GetOneNodeResponseDtoResponseConfigProfile
from .get_one_node_response_dto_response_config_profile_active_inbounds_item import (
    GetOneNodeResponseDtoResponseConfigProfileActiveInboundsItem,
)
from .get_one_node_response_dto_response_provider_type_0 import GetOneNodeResponseDtoResponseProviderType0
from .get_pub_key_response_dto import GetPubKeyResponseDto
from .get_pub_key_response_dto_response import GetPubKeyResponseDtoResponse
from .get_raw_subscription_by_short_uuid_response_dto import GetRawSubscriptionByShortUuidResponseDto
from .get_raw_subscription_by_short_uuid_response_dto_response import GetRawSubscriptionByShortUuidResponseDtoResponse
from .get_raw_subscription_by_short_uuid_response_dto_response_headers import (
    GetRawSubscriptionByShortUuidResponseDtoResponseHeaders,
)
from .get_raw_subscription_by_short_uuid_response_dto_response_raw_hosts_item import (
    GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItem,
)
from .get_raw_subscription_by_short_uuid_response_dto_response_raw_hosts_item_additional_params_type_0 import (
    GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemAdditionalParamsType0,
)
from .get_raw_subscription_by_short_uuid_response_dto_response_raw_hosts_item_db_data import (
    GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemDbData,
)
from .get_raw_subscription_by_short_uuid_response_dto_response_raw_hosts_item_db_data_raw_inbound_type_0 import (
    GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemDbDataRawInboundType0,
)
from .get_raw_subscription_by_short_uuid_response_dto_response_raw_hosts_item_mux_params_type_0 import (
    GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemMuxParamsType0,
)
from .get_raw_subscription_by_short_uuid_response_dto_response_raw_hosts_item_protocol_options_type_0 import (
    GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemProtocolOptionsType0,
)
from .get_raw_subscription_by_short_uuid_response_dto_response_raw_hosts_item_protocol_options_type_0_ss_type_0 import (
    GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemProtocolOptionsType0SsType0,
)
from .get_raw_subscription_by_short_uuid_response_dto_response_raw_hosts_item_sockopt_params_type_0 import (
    GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemSockoptParamsType0,
)
from .get_raw_subscription_by_short_uuid_response_dto_response_raw_hosts_item_x_http_extra_params_type_0 import (
    GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemXHttpExtraParamsType0,
)
from .get_raw_subscription_by_short_uuid_response_dto_response_user import (
    GetRawSubscriptionByShortUuidResponseDtoResponseUser,
)
from .get_raw_subscription_by_short_uuid_response_dto_response_user_traffic_limit_strategy import (
    GetRawSubscriptionByShortUuidResponseDtoResponseUserTrafficLimitStrategy,
)
from .get_raw_subscription_by_short_uuid_response_dto_response_user_user_status import (
    GetRawSubscriptionByShortUuidResponseDtoResponseUserUserStatus,
)
from .get_remnawave_health_response_dto import GetRemnawaveHealthResponseDto
from .get_remnawave_health_response_dto_response import GetRemnawaveHealthResponseDtoResponse
from .get_remnawave_health_response_dto_response_pm_2_stats_item import (
    GetRemnawaveHealthResponseDtoResponsePm2StatsItem,
)
from .get_stats_response_dto import GetStatsResponseDto
from .get_stats_response_dto_response import GetStatsResponseDtoResponse
from .get_stats_response_dto_response_cpu import GetStatsResponseDtoResponseCpu
from .get_stats_response_dto_response_memory import GetStatsResponseDtoResponseMemory
from .get_stats_response_dto_response_nodes import GetStatsResponseDtoResponseNodes
from .get_stats_response_dto_response_online_stats import GetStatsResponseDtoResponseOnlineStats
from .get_stats_response_dto_response_users import GetStatsResponseDtoResponseUsers
from .get_stats_response_dto_response_users_status_counts import GetStatsResponseDtoResponseUsersStatusCounts
from .get_status_response_dto import GetStatusResponseDto
from .get_status_response_dto_response import GetStatusResponseDtoResponse
from .get_status_response_dto_response_oauth_2 import GetStatusResponseDtoResponseOauth2
from .get_status_response_dto_response_oauth_2_providers import GetStatusResponseDtoResponseOauth2Providers
from .get_status_response_dto_response_tg_auth_type_0 import GetStatusResponseDtoResponseTgAuthType0
from .get_subscription_by_username_response_dto import GetSubscriptionByUsernameResponseDto
from .get_subscription_by_username_response_dto_response import GetSubscriptionByUsernameResponseDtoResponse
from .get_subscription_by_username_response_dto_response_ss_conf_links import (
    GetSubscriptionByUsernameResponseDtoResponseSsConfLinks,
)
from .get_subscription_by_username_response_dto_response_user import GetSubscriptionByUsernameResponseDtoResponseUser
from .get_subscription_by_username_response_dto_response_user_traffic_limit_strategy import (
    GetSubscriptionByUsernameResponseDtoResponseUserTrafficLimitStrategy,
)
from .get_subscription_by_username_response_dto_response_user_user_status import (
    GetSubscriptionByUsernameResponseDtoResponseUserUserStatus,
)
from .get_subscription_info_response_dto import GetSubscriptionInfoResponseDto
from .get_subscription_info_response_dto_response import GetSubscriptionInfoResponseDtoResponse
from .get_subscription_info_response_dto_response_happ import GetSubscriptionInfoResponseDtoResponseHapp
from .get_subscription_info_response_dto_response_ss_conf_links import GetSubscriptionInfoResponseDtoResponseSsConfLinks
from .get_subscription_info_response_dto_response_user import GetSubscriptionInfoResponseDtoResponseUser
from .get_subscription_info_response_dto_response_user_traffic_limit_strategy import (
    GetSubscriptionInfoResponseDtoResponseUserTrafficLimitStrategy,
)
from .get_subscription_info_response_dto_response_user_user_status import (
    GetSubscriptionInfoResponseDtoResponseUserUserStatus,
)
from .get_subscription_settings_response_dto import GetSubscriptionSettingsResponseDto
from .get_subscription_settings_response_dto_response import GetSubscriptionSettingsResponseDtoResponse
from .get_subscription_settings_response_dto_response_custom_response_headers_type_0 import (
    GetSubscriptionSettingsResponseDtoResponseCustomResponseHeadersType0,
)
from .get_template_response_dto import GetTemplateResponseDto
from .get_template_response_dto_response import GetTemplateResponseDtoResponse
from .get_template_response_dto_response_template_type import GetTemplateResponseDtoResponseTemplateType
from .get_user_accessible_nodes_response_dto import GetUserAccessibleNodesResponseDto
from .get_user_accessible_nodes_response_dto_response import GetUserAccessibleNodesResponseDtoResponse
from .get_user_accessible_nodes_response_dto_response_active_nodes_item import (
    GetUserAccessibleNodesResponseDtoResponseActiveNodesItem,
)
from .get_user_accessible_nodes_response_dto_response_active_nodes_item_active_squads_item import (
    GetUserAccessibleNodesResponseDtoResponseActiveNodesItemActiveSquadsItem,
)
from .get_user_by_email_response_dto import GetUserByEmailResponseDto
from .get_user_by_email_response_dto_response_item import GetUserByEmailResponseDtoResponseItem
from .get_user_by_email_response_dto_response_item_active_internal_squads_item import (
    GetUserByEmailResponseDtoResponseItemActiveInternalSquadsItem,
)
from .get_user_by_email_response_dto_response_item_happ import GetUserByEmailResponseDtoResponseItemHapp
from .get_user_by_email_response_dto_response_item_last_connected_node_type_0 import (
    GetUserByEmailResponseDtoResponseItemLastConnectedNodeType0,
)
from .get_user_by_email_response_dto_response_item_status import GetUserByEmailResponseDtoResponseItemStatus
from .get_user_by_email_response_dto_response_item_traffic_limit_strategy import (
    GetUserByEmailResponseDtoResponseItemTrafficLimitStrategy,
)
from .get_user_by_short_uuid_response_dto import GetUserByShortUuidResponseDto
from .get_user_by_short_uuid_response_dto_response import GetUserByShortUuidResponseDtoResponse
from .get_user_by_short_uuid_response_dto_response_active_internal_squads_item import (
    GetUserByShortUuidResponseDtoResponseActiveInternalSquadsItem,
)
from .get_user_by_short_uuid_response_dto_response_happ import GetUserByShortUuidResponseDtoResponseHapp
from .get_user_by_short_uuid_response_dto_response_last_connected_node_type_0 import (
    GetUserByShortUuidResponseDtoResponseLastConnectedNodeType0,
)
from .get_user_by_short_uuid_response_dto_response_status import GetUserByShortUuidResponseDtoResponseStatus
from .get_user_by_short_uuid_response_dto_response_traffic_limit_strategy import (
    GetUserByShortUuidResponseDtoResponseTrafficLimitStrategy,
)
from .get_user_by_tag_response_dto import GetUserByTagResponseDto
from .get_user_by_tag_response_dto_response_item import GetUserByTagResponseDtoResponseItem
from .get_user_by_tag_response_dto_response_item_active_internal_squads_item import (
    GetUserByTagResponseDtoResponseItemActiveInternalSquadsItem,
)
from .get_user_by_tag_response_dto_response_item_happ import GetUserByTagResponseDtoResponseItemHapp
from .get_user_by_tag_response_dto_response_item_last_connected_node_type_0 import (
    GetUserByTagResponseDtoResponseItemLastConnectedNodeType0,
)
from .get_user_by_tag_response_dto_response_item_status import GetUserByTagResponseDtoResponseItemStatus
from .get_user_by_tag_response_dto_response_item_traffic_limit_strategy import (
    GetUserByTagResponseDtoResponseItemTrafficLimitStrategy,
)
from .get_user_by_telegram_id_response_dto import GetUserByTelegramIdResponseDto
from .get_user_by_telegram_id_response_dto_response_item import GetUserByTelegramIdResponseDtoResponseItem
from .get_user_by_telegram_id_response_dto_response_item_active_internal_squads_item import (
    GetUserByTelegramIdResponseDtoResponseItemActiveInternalSquadsItem,
)
from .get_user_by_telegram_id_response_dto_response_item_happ import GetUserByTelegramIdResponseDtoResponseItemHapp
from .get_user_by_telegram_id_response_dto_response_item_last_connected_node_type_0 import (
    GetUserByTelegramIdResponseDtoResponseItemLastConnectedNodeType0,
)
from .get_user_by_telegram_id_response_dto_response_item_status import GetUserByTelegramIdResponseDtoResponseItemStatus
from .get_user_by_telegram_id_response_dto_response_item_traffic_limit_strategy import (
    GetUserByTelegramIdResponseDtoResponseItemTrafficLimitStrategy,
)
from .get_user_by_username_response_dto import GetUserByUsernameResponseDto
from .get_user_by_username_response_dto_response import GetUserByUsernameResponseDtoResponse
from .get_user_by_username_response_dto_response_active_internal_squads_item import (
    GetUserByUsernameResponseDtoResponseActiveInternalSquadsItem,
)
from .get_user_by_username_response_dto_response_happ import GetUserByUsernameResponseDtoResponseHapp
from .get_user_by_username_response_dto_response_last_connected_node_type_0 import (
    GetUserByUsernameResponseDtoResponseLastConnectedNodeType0,
)
from .get_user_by_username_response_dto_response_status import GetUserByUsernameResponseDtoResponseStatus
from .get_user_by_username_response_dto_response_traffic_limit_strategy import (
    GetUserByUsernameResponseDtoResponseTrafficLimitStrategy,
)
from .get_user_by_uuid_response_dto import GetUserByUuidResponseDto
from .get_user_by_uuid_response_dto_response import GetUserByUuidResponseDtoResponse
from .get_user_by_uuid_response_dto_response_active_internal_squads_item import (
    GetUserByUuidResponseDtoResponseActiveInternalSquadsItem,
)
from .get_user_by_uuid_response_dto_response_happ import GetUserByUuidResponseDtoResponseHapp
from .get_user_by_uuid_response_dto_response_last_connected_node_type_0 import (
    GetUserByUuidResponseDtoResponseLastConnectedNodeType0,
)
from .get_user_by_uuid_response_dto_response_status import GetUserByUuidResponseDtoResponseStatus
from .get_user_by_uuid_response_dto_response_traffic_limit_strategy import (
    GetUserByUuidResponseDtoResponseTrafficLimitStrategy,
)
from .get_user_hwid_devices_response_dto import GetUserHwidDevicesResponseDto
from .get_user_hwid_devices_response_dto_response import GetUserHwidDevicesResponseDtoResponse
from .get_user_hwid_devices_response_dto_response_devices_item import GetUserHwidDevicesResponseDtoResponseDevicesItem
from .get_user_usage_by_range_response_dto import GetUserUsageByRangeResponseDto
from .get_user_usage_by_range_response_dto_response_item import GetUserUsageByRangeResponseDtoResponseItem
from .hosts_bulk_actions_controller_delete_hosts_response_500 import HostsBulkActionsControllerDeleteHostsResponse500
from .hosts_bulk_actions_controller_disable_hosts_response_500 import HostsBulkActionsControllerDisableHostsResponse500
from .hosts_bulk_actions_controller_enable_hosts_response_500 import HostsBulkActionsControllerEnableHostsResponse500
from .hosts_bulk_actions_controller_set_inbound_to_hosts_response_500 import (
    HostsBulkActionsControllerSetInboundToHostsResponse500,
)
from .hosts_bulk_actions_controller_set_port_to_hosts_response_500 import (
    HostsBulkActionsControllerSetPortToHostsResponse500,
)
from .hosts_controller_create_host_response_500 import HostsControllerCreateHostResponse500
from .hosts_controller_delete_host_response_500 import HostsControllerDeleteHostResponse500
from .hosts_controller_get_all_host_tags_response_500 import HostsControllerGetAllHostTagsResponse500
from .hosts_controller_get_all_hosts_response_500 import HostsControllerGetAllHostsResponse500
from .hosts_controller_get_one_host_response_500 import HostsControllerGetOneHostResponse500
from .hosts_controller_reorder_hosts_response_500 import HostsControllerReorderHostsResponse500
from .hosts_controller_update_host_response_500 import HostsControllerUpdateHostResponse500
from .hwid_user_devices_controller_create_user_hwid_device_response_500 import (
    HwidUserDevicesControllerCreateUserHwidDeviceResponse500,
)
from .hwid_user_devices_controller_delete_user_hwid_device_response_500 import (
    HwidUserDevicesControllerDeleteUserHwidDeviceResponse500,
)
from .hwid_user_devices_controller_get_user_hwid_devices_response_500 import (
    HwidUserDevicesControllerGetUserHwidDevicesResponse500,
)
from .infra_billing_controller_create_infra_billing_history_record_response_500 import (
    InfraBillingControllerCreateInfraBillingHistoryRecordResponse500,
)
from .infra_billing_controller_create_infra_billing_node_response_500 import (
    InfraBillingControllerCreateInfraBillingNodeResponse500,
)
from .infra_billing_controller_create_infra_provider_response_500 import (
    InfraBillingControllerCreateInfraProviderResponse500,
)
from .infra_billing_controller_delete_infra_billing_history_record_by_uuid_response_500 import (
    InfraBillingControllerDeleteInfraBillingHistoryRecordByUuidResponse500,
)
from .infra_billing_controller_delete_infra_billing_node_by_uuid_response_500 import (
    InfraBillingControllerDeleteInfraBillingNodeByUuidResponse500,
)
from .infra_billing_controller_delete_infra_provider_by_uuid_response_500 import (
    InfraBillingControllerDeleteInfraProviderByUuidResponse500,
)
from .infra_billing_controller_get_billing_nodes_response_500 import InfraBillingControllerGetBillingNodesResponse500
from .infra_billing_controller_get_infra_billing_history_records_response_500 import (
    InfraBillingControllerGetInfraBillingHistoryRecordsResponse500,
)
from .infra_billing_controller_get_infra_provider_by_uuid_response_500 import (
    InfraBillingControllerGetInfraProviderByUuidResponse500,
)
from .infra_billing_controller_get_infra_providers_response_500 import (
    InfraBillingControllerGetInfraProvidersResponse500,
)
from .infra_billing_controller_update_infra_billing_node_response_500 import (
    InfraBillingControllerUpdateInfraBillingNodeResponse500,
)
from .infra_billing_controller_update_infra_provider_response_500 import (
    InfraBillingControllerUpdateInfraProviderResponse500,
)
from .internal_squad_controller_add_users_to_internal_squad_response_500 import (
    InternalSquadControllerAddUsersToInternalSquadResponse500,
)
from .internal_squad_controller_create_internal_squad_response_500 import (
    InternalSquadControllerCreateInternalSquadResponse500,
)
from .internal_squad_controller_delete_internal_squad_response_500 import (
    InternalSquadControllerDeleteInternalSquadResponse500,
)
from .internal_squad_controller_get_internal_squad_accessible_nodes_response_500 import (
    InternalSquadControllerGetInternalSquadAccessibleNodesResponse500,
)
from .internal_squad_controller_get_internal_squad_by_uuid_response_500 import (
    InternalSquadControllerGetInternalSquadByUuidResponse500,
)
from .internal_squad_controller_get_internal_squads_response_500 import (
    InternalSquadControllerGetInternalSquadsResponse500,
)
from .internal_squad_controller_remove_users_from_internal_squad_response_500 import (
    InternalSquadControllerRemoveUsersFromInternalSquadResponse500,
)
from .internal_squad_controller_update_internal_squad_response_500 import (
    InternalSquadControllerUpdateInternalSquadResponse500,
)
from .keygen_controller_generate_key_response_500 import KeygenControllerGenerateKeyResponse500
from .login_request_dto import LoginRequestDto
from .login_response_dto import LoginResponseDto
from .login_response_dto_response import LoginResponseDtoResponse
from .nodes_controller_create_node_response_500 import NodesControllerCreateNodeResponse500
from .nodes_controller_delete_node_response_500 import NodesControllerDeleteNodeResponse500
from .nodes_controller_disable_node_response_500 import NodesControllerDisableNodeResponse500
from .nodes_controller_enable_node_response_500 import NodesControllerEnableNodeResponse500
from .nodes_controller_get_all_nodes_response_500 import NodesControllerGetAllNodesResponse500
from .nodes_controller_get_one_node_response_500 import NodesControllerGetOneNodeResponse500
from .nodes_controller_reorder_nodes_response_500 import NodesControllerReorderNodesResponse500
from .nodes_controller_restart_all_nodes_response_500 import NodesControllerRestartAllNodesResponse500
from .nodes_controller_restart_node_response_500 import NodesControllerRestartNodeResponse500
from .nodes_controller_update_node_response_500 import NodesControllerUpdateNodeResponse500
from .nodes_usage_history_controller_get_nodes_usage_by_range_response_500 import (
    NodesUsageHistoryControllerGetNodesUsageByRangeResponse500,
)
from .nodes_user_usage_history_controller_get_node_user_usage_response_500 import (
    NodesUserUsageHistoryControllerGetNodeUserUsageResponse500,
)
from .nodes_user_usage_history_controller_get_nodes_realtime_usage_response_500 import (
    NodesUserUsageHistoryControllerGetNodesRealtimeUsageResponse500,
)
from .o_auth_2_authorize_request_dto import OAuth2AuthorizeRequestDto
from .o_auth_2_authorize_request_dto_provider import OAuth2AuthorizeRequestDtoProvider
from .o_auth_2_authorize_response_dto import OAuth2AuthorizeResponseDto
from .o_auth_2_authorize_response_dto_response import OAuth2AuthorizeResponseDtoResponse
from .o_auth_2_callback_request_dto import OAuth2CallbackRequestDto
from .o_auth_2_callback_request_dto_provider import OAuth2CallbackRequestDtoProvider
from .o_auth_2_callback_response_dto import OAuth2CallbackResponseDto
from .o_auth_2_callback_response_dto_response import OAuth2CallbackResponseDtoResponse
from .register_request_dto import RegisterRequestDto
from .register_response_dto import RegisterResponseDto
from .register_response_dto_response import RegisterResponseDtoResponse
from .remove_users_from_internal_squad_response_dto import RemoveUsersFromInternalSquadResponseDto
from .remove_users_from_internal_squad_response_dto_response import RemoveUsersFromInternalSquadResponseDtoResponse
from .reorder_host_request_dto import ReorderHostRequestDto
from .reorder_host_request_dto_hosts_item import ReorderHostRequestDtoHostsItem
from .reorder_host_response_dto import ReorderHostResponseDto
from .reorder_host_response_dto_response import ReorderHostResponseDtoResponse
from .reorder_node_request_dto import ReorderNodeRequestDto
from .reorder_node_request_dto_nodes_item import ReorderNodeRequestDtoNodesItem
from .reorder_node_response_dto import ReorderNodeResponseDto
from .reorder_node_response_dto_response_item import ReorderNodeResponseDtoResponseItem
from .reorder_node_response_dto_response_item_config_profile import ReorderNodeResponseDtoResponseItemConfigProfile
from .reorder_node_response_dto_response_item_config_profile_active_inbounds_item import (
    ReorderNodeResponseDtoResponseItemConfigProfileActiveInboundsItem,
)
from .reorder_node_response_dto_response_item_provider_type_0 import ReorderNodeResponseDtoResponseItemProviderType0
from .reset_user_traffic_response_dto import ResetUserTrafficResponseDto
from .reset_user_traffic_response_dto_response import ResetUserTrafficResponseDtoResponse
from .reset_user_traffic_response_dto_response_active_internal_squads_item import (
    ResetUserTrafficResponseDtoResponseActiveInternalSquadsItem,
)
from .reset_user_traffic_response_dto_response_happ import ResetUserTrafficResponseDtoResponseHapp
from .reset_user_traffic_response_dto_response_last_connected_node_type_0 import (
    ResetUserTrafficResponseDtoResponseLastConnectedNodeType0,
)
from .reset_user_traffic_response_dto_response_status import ResetUserTrafficResponseDtoResponseStatus
from .reset_user_traffic_response_dto_response_traffic_limit_strategy import (
    ResetUserTrafficResponseDtoResponseTrafficLimitStrategy,
)
from .restart_all_nodes_response_dto import RestartAllNodesResponseDto
from .restart_all_nodes_response_dto_response import RestartAllNodesResponseDtoResponse
from .restart_node_response_dto import RestartNodeResponseDto
from .restart_node_response_dto_response import RestartNodeResponseDtoResponse
from .revoke_user_subscription_body_dto import RevokeUserSubscriptionBodyDto
from .revoke_user_subscription_response_dto import RevokeUserSubscriptionResponseDto
from .revoke_user_subscription_response_dto_response import RevokeUserSubscriptionResponseDtoResponse
from .revoke_user_subscription_response_dto_response_active_internal_squads_item import (
    RevokeUserSubscriptionResponseDtoResponseActiveInternalSquadsItem,
)
from .revoke_user_subscription_response_dto_response_happ import RevokeUserSubscriptionResponseDtoResponseHapp
from .revoke_user_subscription_response_dto_response_last_connected_node_type_0 import (
    RevokeUserSubscriptionResponseDtoResponseLastConnectedNodeType0,
)
from .revoke_user_subscription_response_dto_response_status import RevokeUserSubscriptionResponseDtoResponseStatus
from .revoke_user_subscription_response_dto_response_traffic_limit_strategy import (
    RevokeUserSubscriptionResponseDtoResponseTrafficLimitStrategy,
)
from .set_inbound_to_many_hosts_request_dto import SetInboundToManyHostsRequestDto
from .set_inbound_to_many_hosts_response_dto import SetInboundToManyHostsResponseDto
from .set_inbound_to_many_hosts_response_dto_response_item import SetInboundToManyHostsResponseDtoResponseItem
from .set_inbound_to_many_hosts_response_dto_response_item_inbound import (
    SetInboundToManyHostsResponseDtoResponseItemInbound,
)
from .set_inbound_to_many_hosts_response_dto_response_item_security_layer import (
    SetInboundToManyHostsResponseDtoResponseItemSecurityLayer,
)
from .set_port_to_many_hosts_request_dto import SetPortToManyHostsRequestDto
from .set_port_to_many_hosts_response_dto import SetPortToManyHostsResponseDto
from .set_port_to_many_hosts_response_dto_response_item import SetPortToManyHostsResponseDtoResponseItem
from .set_port_to_many_hosts_response_dto_response_item_inbound import SetPortToManyHostsResponseDtoResponseItemInbound
from .set_port_to_many_hosts_response_dto_response_item_security_layer import (
    SetPortToManyHostsResponseDtoResponseItemSecurityLayer,
)
from .subscription_controller_get_raw_subscription_by_short_uuid_response_500 import (
    SubscriptionControllerGetRawSubscriptionByShortUuidResponse500,
)
from .subscription_controller_get_subscription_by_client_type_client_type import (
    SubscriptionControllerGetSubscriptionByClientTypeClientType,
)
from .subscription_controller_get_subscription_info_by_short_uuid_response_500 import (
    SubscriptionControllerGetSubscriptionInfoByShortUuidResponse500,
)
from .subscription_settings_controller_get_settings_response_500 import (
    SubscriptionSettingsControllerGetSettingsResponse500,
)
from .subscription_settings_controller_update_settings_response_500 import (
    SubscriptionSettingsControllerUpdateSettingsResponse500,
)
from .subscription_template_controller_get_template_response_500 import (
    SubscriptionTemplateControllerGetTemplateResponse500,
)
from .subscription_template_controller_get_template_template_type import (
    SubscriptionTemplateControllerGetTemplateTemplateType,
)
from .subscription_template_controller_update_template_response_500 import (
    SubscriptionTemplateControllerUpdateTemplateResponse500,
)
from .subscriptions_controller_get_all_subscriptions_response_500 import (
    SubscriptionsControllerGetAllSubscriptionsResponse500,
)
from .subscriptions_controller_get_subscription_by_username_response_404 import (
    SubscriptionsControllerGetSubscriptionByUsernameResponse404,
)
from .subscriptions_controller_get_subscription_by_username_response_500 import (
    SubscriptionsControllerGetSubscriptionByUsernameResponse500,
)
from .system_controller_get_bandwidth_stats_response_500 import SystemControllerGetBandwidthStatsResponse500
from .system_controller_get_nodes_metrics_response_500 import SystemControllerGetNodesMetricsResponse500
from .system_controller_get_nodes_statistics_response_500 import SystemControllerGetNodesStatisticsResponse500
from .system_controller_get_remnawave_health_response_500 import SystemControllerGetRemnawaveHealthResponse500
from .system_controller_get_stats_response_500 import SystemControllerGetStatsResponse500
from .telegram_callback_request_dto import TelegramCallbackRequestDto
from .telegram_callback_response_dto import TelegramCallbackResponseDto
from .telegram_callback_response_dto_response import TelegramCallbackResponseDtoResponse
from .update_config_profile_request_dto import UpdateConfigProfileRequestDto
from .update_config_profile_request_dto_config import UpdateConfigProfileRequestDtoConfig
from .update_config_profile_response_dto import UpdateConfigProfileResponseDto
from .update_config_profile_response_dto_response import UpdateConfigProfileResponseDtoResponse
from .update_config_profile_response_dto_response_inbounds_item import (
    UpdateConfigProfileResponseDtoResponseInboundsItem,
)
from .update_config_profile_response_dto_response_nodes_item import UpdateConfigProfileResponseDtoResponseNodesItem
from .update_host_request_dto import UpdateHostRequestDto
from .update_host_request_dto_alpn import UpdateHostRequestDtoAlpn
from .update_host_request_dto_fingerprint import UpdateHostRequestDtoFingerprint
from .update_host_request_dto_inbound import UpdateHostRequestDtoInbound
from .update_host_request_dto_security_layer import UpdateHostRequestDtoSecurityLayer
from .update_host_response_dto import UpdateHostResponseDto
from .update_host_response_dto_response import UpdateHostResponseDtoResponse
from .update_host_response_dto_response_inbound import UpdateHostResponseDtoResponseInbound
from .update_host_response_dto_response_security_layer import UpdateHostResponseDtoResponseSecurityLayer
from .update_infra_billing_node_request_dto import UpdateInfraBillingNodeRequestDto
from .update_infra_billing_node_response_dto import UpdateInfraBillingNodeResponseDto
from .update_infra_billing_node_response_dto_response import UpdateInfraBillingNodeResponseDtoResponse
from .update_infra_billing_node_response_dto_response_available_billing_nodes_item import (
    UpdateInfraBillingNodeResponseDtoResponseAvailableBillingNodesItem,
)
from .update_infra_billing_node_response_dto_response_billing_nodes_item import (
    UpdateInfraBillingNodeResponseDtoResponseBillingNodesItem,
)
from .update_infra_billing_node_response_dto_response_billing_nodes_item_node import (
    UpdateInfraBillingNodeResponseDtoResponseBillingNodesItemNode,
)
from .update_infra_billing_node_response_dto_response_billing_nodes_item_provider import (
    UpdateInfraBillingNodeResponseDtoResponseBillingNodesItemProvider,
)
from .update_infra_billing_node_response_dto_response_stats import UpdateInfraBillingNodeResponseDtoResponseStats
from .update_infra_provider_request_dto import UpdateInfraProviderRequestDto
from .update_infra_provider_response_dto import UpdateInfraProviderResponseDto
from .update_infra_provider_response_dto_response import UpdateInfraProviderResponseDtoResponse
from .update_infra_provider_response_dto_response_billing_history import (
    UpdateInfraProviderResponseDtoResponseBillingHistory,
)
from .update_infra_provider_response_dto_response_billing_nodes_item import (
    UpdateInfraProviderResponseDtoResponseBillingNodesItem,
)
from .update_internal_squad_request_dto import UpdateInternalSquadRequestDto
from .update_internal_squad_response_dto import UpdateInternalSquadResponseDto
from .update_internal_squad_response_dto_response import UpdateInternalSquadResponseDtoResponse
from .update_internal_squad_response_dto_response_inbounds_item import (
    UpdateInternalSquadResponseDtoResponseInboundsItem,
)
from .update_internal_squad_response_dto_response_info import UpdateInternalSquadResponseDtoResponseInfo
from .update_node_request_dto import UpdateNodeRequestDto
from .update_node_request_dto_config_profile import UpdateNodeRequestDtoConfigProfile
from .update_node_response_dto import UpdateNodeResponseDto
from .update_node_response_dto_response import UpdateNodeResponseDtoResponse
from .update_node_response_dto_response_config_profile import UpdateNodeResponseDtoResponseConfigProfile
from .update_node_response_dto_response_config_profile_active_inbounds_item import (
    UpdateNodeResponseDtoResponseConfigProfileActiveInboundsItem,
)
from .update_node_response_dto_response_provider_type_0 import UpdateNodeResponseDtoResponseProviderType0
from .update_subscription_settings_request_dto import UpdateSubscriptionSettingsRequestDto
from .update_subscription_settings_request_dto_custom_response_headers import (
    UpdateSubscriptionSettingsRequestDtoCustomResponseHeaders,
)
from .update_subscription_settings_response_dto import UpdateSubscriptionSettingsResponseDto
from .update_subscription_settings_response_dto_response import UpdateSubscriptionSettingsResponseDtoResponse
from .update_subscription_settings_response_dto_response_custom_response_headers_type_0 import (
    UpdateSubscriptionSettingsResponseDtoResponseCustomResponseHeadersType0,
)
from .update_template_request_dto import UpdateTemplateRequestDto
from .update_template_request_dto_template_json import UpdateTemplateRequestDtoTemplateJson
from .update_template_request_dto_template_type import UpdateTemplateRequestDtoTemplateType
from .update_template_response_dto import UpdateTemplateResponseDto
from .update_template_response_dto_response import UpdateTemplateResponseDtoResponse
from .update_template_response_dto_response_template_type import UpdateTemplateResponseDtoResponseTemplateType
from .update_user_request_dto import UpdateUserRequestDto
from .update_user_request_dto_status import UpdateUserRequestDtoStatus
from .update_user_request_dto_traffic_limit_strategy import UpdateUserRequestDtoTrafficLimitStrategy
from .update_user_response_dto import UpdateUserResponseDto
from .update_user_response_dto_response import UpdateUserResponseDtoResponse
from .update_user_response_dto_response_active_internal_squads_item import (
    UpdateUserResponseDtoResponseActiveInternalSquadsItem,
)
from .update_user_response_dto_response_happ import UpdateUserResponseDtoResponseHapp
from .update_user_response_dto_response_last_connected_node_type_0 import (
    UpdateUserResponseDtoResponseLastConnectedNodeType0,
)
from .update_user_response_dto_response_status import UpdateUserResponseDtoResponseStatus
from .update_user_response_dto_response_traffic_limit_strategy import UpdateUserResponseDtoResponseTrafficLimitStrategy
from .users_bulk_actions_controller_bulk_all_reset_user_traffic_response_500 import (
    UsersBulkActionsControllerBulkAllResetUserTrafficResponse500,
)
from .users_bulk_actions_controller_bulk_delete_users_by_status_response_500 import (
    UsersBulkActionsControllerBulkDeleteUsersByStatusResponse500,
)
from .users_bulk_actions_controller_bulk_delete_users_response_500 import (
    UsersBulkActionsControllerBulkDeleteUsersResponse500,
)
from .users_bulk_actions_controller_bulk_reset_user_traffic_response_500 import (
    UsersBulkActionsControllerBulkResetUserTrafficResponse500,
)
from .users_bulk_actions_controller_bulk_revoke_users_subscription_response_500 import (
    UsersBulkActionsControllerBulkRevokeUsersSubscriptionResponse500,
)
from .users_bulk_actions_controller_bulk_update_all_users_response_500 import (
    UsersBulkActionsControllerBulkUpdateAllUsersResponse500,
)
from .users_bulk_actions_controller_bulk_update_users_internal_squads_response_500 import (
    UsersBulkActionsControllerBulkUpdateUsersInternalSquadsResponse500,
)
from .users_bulk_actions_controller_bulk_update_users_response_500 import (
    UsersBulkActionsControllerBulkUpdateUsersResponse500,
)
from .users_controller_create_user_response_500 import UsersControllerCreateUserResponse500
from .users_controller_delete_user_response_500 import UsersControllerDeleteUserResponse500
from .users_controller_disable_user_response_500 import UsersControllerDisableUserResponse500
from .users_controller_enable_user_response_500 import UsersControllerEnableUserResponse500
from .users_controller_get_all_tags_response_500 import UsersControllerGetAllTagsResponse500
from .users_controller_get_all_users_response_500 import UsersControllerGetAllUsersResponse500
from .users_controller_get_user_accessible_nodes_response_500 import UsersControllerGetUserAccessibleNodesResponse500
from .users_controller_get_user_by_short_uuid_response_500 import UsersControllerGetUserByShortUuidResponse500
from .users_controller_get_user_by_telegram_id_response_500 import UsersControllerGetUserByTelegramIdResponse500
from .users_controller_get_user_by_username_response_500 import UsersControllerGetUserByUsernameResponse500
from .users_controller_get_user_by_uuid_response_500 import UsersControllerGetUserByUuidResponse500
from .users_controller_get_users_by_email_response_500 import UsersControllerGetUsersByEmailResponse500
from .users_controller_get_users_by_tag_response_500 import UsersControllerGetUsersByTagResponse500
from .users_controller_reset_user_traffic_response_500 import UsersControllerResetUserTrafficResponse500
from .users_controller_revoke_user_subscription_response_500 import UsersControllerRevokeUserSubscriptionResponse500
from .users_controller_update_user_response_500 import UsersControllerUpdateUserResponse500
from .users_stats_controller_get_user_usage_by_range_response_500 import (
    UsersStatsControllerGetUserUsageByRangeResponse500,
)

__all__ = (
    "AddUsersToInternalSquadResponseDto",
    "AddUsersToInternalSquadResponseDtoResponse",
    "ApiTokensControllerCreateResponse500",
    "ApiTokensControllerDeleteResponse500",
    "ApiTokensControllerFindAllResponse500",
    "AuthControllerGetStatusResponse500",
    "AuthControllerLoginResponse401",
    "AuthControllerLoginResponse500",
    "AuthControllerOauth2AuthorizeResponse500",
    "AuthControllerOauth2CallbackResponse500",
    "AuthControllerRegisterResponse403",
    "AuthControllerRegisterResponse500",
    "AuthControllerTelegramCallbackResponse500",
    "BulkAllResetTrafficUsersResponseDto",
    "BulkAllResetTrafficUsersResponseDtoResponse",
    "BulkAllUpdateUsersRequestDto",
    "BulkAllUpdateUsersRequestDtoStatus",
    "BulkAllUpdateUsersRequestDtoTrafficLimitStrategy",
    "BulkAllUpdateUsersResponseDto",
    "BulkAllUpdateUsersResponseDtoResponse",
    "BulkDeleteHostsRequestDto",
    "BulkDeleteHostsResponseDto",
    "BulkDeleteHostsResponseDtoResponseItem",
    "BulkDeleteHostsResponseDtoResponseItemInbound",
    "BulkDeleteHostsResponseDtoResponseItemSecurityLayer",
    "BulkDeleteUsersByStatusRequestDto",
    "BulkDeleteUsersByStatusRequestDtoStatus",
    "BulkDeleteUsersByStatusResponseDto",
    "BulkDeleteUsersByStatusResponseDtoResponse",
    "BulkDeleteUsersRequestDto",
    "BulkDeleteUsersResponseDto",
    "BulkDeleteUsersResponseDtoResponse",
    "BulkDisableHostsRequestDto",
    "BulkDisableHostsResponseDto",
    "BulkDisableHostsResponseDtoResponseItem",
    "BulkDisableHostsResponseDtoResponseItemInbound",
    "BulkDisableHostsResponseDtoResponseItemSecurityLayer",
    "BulkEnableHostsRequestDto",
    "BulkEnableHostsResponseDto",
    "BulkEnableHostsResponseDtoResponseItem",
    "BulkEnableHostsResponseDtoResponseItemInbound",
    "BulkEnableHostsResponseDtoResponseItemSecurityLayer",
    "BulkResetTrafficUsersRequestDto",
    "BulkResetTrafficUsersResponseDto",
    "BulkResetTrafficUsersResponseDtoResponse",
    "BulkRevokeUsersSubscriptionRequestDto",
    "BulkRevokeUsersSubscriptionResponseDto",
    "BulkRevokeUsersSubscriptionResponseDtoResponse",
    "BulkUpdateUsersRequestDto",
    "BulkUpdateUsersRequestDtoFields",
    "BulkUpdateUsersRequestDtoFieldsStatus",
    "BulkUpdateUsersRequestDtoFieldsTrafficLimitStrategy",
    "BulkUpdateUsersResponseDto",
    "BulkUpdateUsersResponseDtoResponse",
    "BulkUpdateUsersSquadsRequestDto",
    "BulkUpdateUsersSquadsResponseDto",
    "BulkUpdateUsersSquadsResponseDtoResponse",
    "ConfigProfileControllerCreateConfigProfileResponse500",
    "ConfigProfileControllerDeleteConfigProfileByUuidResponse500",
    "ConfigProfileControllerGetAllInboundsResponse500",
    "ConfigProfileControllerGetConfigProfileByUuidResponse500",
    "ConfigProfileControllerGetConfigProfilesResponse500",
    "ConfigProfileControllerGetInboundsByProfileUuidResponse500",
    "ConfigProfileControllerUpdateConfigProfileResponse500",
    "CreateApiTokenRequestDto",
    "CreateApiTokenResponseDto",
    "CreateApiTokenResponseDtoResponse",
    "CreateConfigProfileRequestDto",
    "CreateConfigProfileRequestDtoConfig",
    "CreateConfigProfileResponseDto",
    "CreateConfigProfileResponseDtoResponse",
    "CreateConfigProfileResponseDtoResponseInboundsItem",
    "CreateConfigProfileResponseDtoResponseNodesItem",
    "CreateHostRequestDto",
    "CreateHostRequestDtoAlpn",
    "CreateHostRequestDtoFingerprint",
    "CreateHostRequestDtoInbound",
    "CreateHostRequestDtoSecurityLayer",
    "CreateHostResponseDto",
    "CreateHostResponseDtoResponse",
    "CreateHostResponseDtoResponseInbound",
    "CreateHostResponseDtoResponseSecurityLayer",
    "CreateInfraBillingHistoryRecordRequestDto",
    "CreateInfraBillingHistoryRecordResponseDto",
    "CreateInfraBillingHistoryRecordResponseDtoResponse",
    "CreateInfraBillingHistoryRecordResponseDtoResponseRecordsItem",
    "CreateInfraBillingHistoryRecordResponseDtoResponseRecordsItemProvider",
    "CreateInfraBillingNodeRequestDto",
    "CreateInfraBillingNodeResponseDto",
    "CreateInfraBillingNodeResponseDtoResponse",
    "CreateInfraBillingNodeResponseDtoResponseAvailableBillingNodesItem",
    "CreateInfraBillingNodeResponseDtoResponseBillingNodesItem",
    "CreateInfraBillingNodeResponseDtoResponseBillingNodesItemNode",
    "CreateInfraBillingNodeResponseDtoResponseBillingNodesItemProvider",
    "CreateInfraBillingNodeResponseDtoResponseStats",
    "CreateInfraProviderRequestDto",
    "CreateInfraProviderResponseDto",
    "CreateInfraProviderResponseDtoResponse",
    "CreateInfraProviderResponseDtoResponseBillingHistory",
    "CreateInfraProviderResponseDtoResponseBillingNodesItem",
    "CreateInternalSquadRequestDto",
    "CreateInternalSquadResponseDto",
    "CreateInternalSquadResponseDtoResponse",
    "CreateInternalSquadResponseDtoResponseInboundsItem",
    "CreateInternalSquadResponseDtoResponseInfo",
    "CreateNodeRequestDto",
    "CreateNodeRequestDtoConfigProfile",
    "CreateNodeResponseDto",
    "CreateNodeResponseDtoResponse",
    "CreateNodeResponseDtoResponseConfigProfile",
    "CreateNodeResponseDtoResponseConfigProfileActiveInboundsItem",
    "CreateNodeResponseDtoResponseProviderType0",
    "CreateUserHwidDeviceRequestDto",
    "CreateUserHwidDeviceResponseDto",
    "CreateUserHwidDeviceResponseDtoResponse",
    "CreateUserHwidDeviceResponseDtoResponseDevicesItem",
    "CreateUserRequestDto",
    "CreateUserRequestDtoStatus",
    "CreateUserRequestDtoTrafficLimitStrategy",
    "CreateUserResponseDto",
    "CreateUserResponseDtoResponse",
    "CreateUserResponseDtoResponseActiveInternalSquadsItem",
    "CreateUserResponseDtoResponseHapp",
    "CreateUserResponseDtoResponseLastConnectedNodeType0",
    "CreateUserResponseDtoResponseStatus",
    "CreateUserResponseDtoResponseTrafficLimitStrategy",
    "DeleteApiTokenResponseDto",
    "DeleteConfigProfileResponseDto",
    "DeleteConfigProfileResponseDtoResponse",
    "DeleteHostResponseDto",
    "DeleteHostResponseDtoResponse",
    "DeleteInfraBillingHistoryRecordByUuidResponseDto",
    "DeleteInfraBillingHistoryRecordByUuidResponseDtoResponse",
    "DeleteInfraBillingHistoryRecordByUuidResponseDtoResponseRecordsItem",
    "DeleteInfraBillingHistoryRecordByUuidResponseDtoResponseRecordsItemProvider",
    "DeleteInfraBillingNodeByUuidResponseDto",
    "DeleteInfraBillingNodeByUuidResponseDtoResponse",
    "DeleteInfraBillingNodeByUuidResponseDtoResponseAvailableBillingNodesItem",
    "DeleteInfraBillingNodeByUuidResponseDtoResponseBillingNodesItem",
    "DeleteInfraBillingNodeByUuidResponseDtoResponseBillingNodesItemNode",
    "DeleteInfraBillingNodeByUuidResponseDtoResponseBillingNodesItemProvider",
    "DeleteInfraBillingNodeByUuidResponseDtoResponseStats",
    "DeleteInfraProviderByUuidResponseDto",
    "DeleteInfraProviderByUuidResponseDtoResponse",
    "DeleteInternalSquadResponseDto",
    "DeleteInternalSquadResponseDtoResponse",
    "DeleteNodeResponseDto",
    "DeleteNodeResponseDtoResponse",
    "DeleteUserHwidDeviceRequestDto",
    "DeleteUserHwidDeviceResponseDto",
    "DeleteUserHwidDeviceResponseDtoResponse",
    "DeleteUserHwidDeviceResponseDtoResponseDevicesItem",
    "DeleteUserResponseDto",
    "DeleteUserResponseDtoResponse",
    "DisableNodeResponseDto",
    "DisableNodeResponseDtoResponse",
    "DisableNodeResponseDtoResponseConfigProfile",
    "DisableNodeResponseDtoResponseConfigProfileActiveInboundsItem",
    "DisableNodeResponseDtoResponseProviderType0",
    "DisableUserResponseDto",
    "DisableUserResponseDtoResponse",
    "DisableUserResponseDtoResponseActiveInternalSquadsItem",
    "DisableUserResponseDtoResponseHapp",
    "DisableUserResponseDtoResponseLastConnectedNodeType0",
    "DisableUserResponseDtoResponseStatus",
    "DisableUserResponseDtoResponseTrafficLimitStrategy",
    "EnableNodeResponseDto",
    "EnableNodeResponseDtoResponse",
    "EnableNodeResponseDtoResponseConfigProfile",
    "EnableNodeResponseDtoResponseConfigProfileActiveInboundsItem",
    "EnableNodeResponseDtoResponseProviderType0",
    "EnableUserResponseDto",
    "EnableUserResponseDtoResponse",
    "EnableUserResponseDtoResponseActiveInternalSquadsItem",
    "EnableUserResponseDtoResponseHapp",
    "EnableUserResponseDtoResponseLastConnectedNodeType0",
    "EnableUserResponseDtoResponseStatus",
    "EnableUserResponseDtoResponseTrafficLimitStrategy",
    "FindAllApiTokensResponseDto",
    "FindAllApiTokensResponseDtoResponse",
    "FindAllApiTokensResponseDtoResponseApiKeysItem",
    "FindAllApiTokensResponseDtoResponseDocs",
    "GetAllHostsResponseDto",
    "GetAllHostsResponseDtoResponseItem",
    "GetAllHostsResponseDtoResponseItemInbound",
    "GetAllHostsResponseDtoResponseItemSecurityLayer",
    "GetAllHostTagsResponseDto",
    "GetAllHostTagsResponseDtoResponse",
    "GetAllInboundsResponseDto",
    "GetAllInboundsResponseDtoResponse",
    "GetAllInboundsResponseDtoResponseInboundsItem",
    "GetAllNodesResponseDto",
    "GetAllNodesResponseDtoResponseItem",
    "GetAllNodesResponseDtoResponseItemConfigProfile",
    "GetAllNodesResponseDtoResponseItemConfigProfileActiveInboundsItem",
    "GetAllNodesResponseDtoResponseItemProviderType0",
    "GetAllSubscriptionsResponseDto",
    "GetAllSubscriptionsResponseDtoResponse",
    "GetAllSubscriptionsResponseDtoResponseSubscriptionsItem",
    "GetAllSubscriptionsResponseDtoResponseSubscriptionsItemSsConfLinks",
    "GetAllSubscriptionsResponseDtoResponseSubscriptionsItemUser",
    "GetAllSubscriptionsResponseDtoResponseSubscriptionsItemUserTrafficLimitStrategy",
    "GetAllSubscriptionsResponseDtoResponseSubscriptionsItemUserUserStatus",
    "GetAllTagsResponseDto",
    "GetAllTagsResponseDtoResponse",
    "GetAllUsersResponseDto",
    "GetAllUsersResponseDtoResponse",
    "GetAllUsersResponseDtoResponseUsersItem",
    "GetAllUsersResponseDtoResponseUsersItemActiveInternalSquadsItem",
    "GetAllUsersResponseDtoResponseUsersItemHapp",
    "GetAllUsersResponseDtoResponseUsersItemLastConnectedNodeType0",
    "GetAllUsersResponseDtoResponseUsersItemStatus",
    "GetAllUsersResponseDtoResponseUsersItemTrafficLimitStrategy",
    "GetBandwidthStatsResponseDto",
    "GetBandwidthStatsResponseDtoResponse",
    "GetBandwidthStatsResponseDtoResponseBandwidthCalendarMonth",
    "GetBandwidthStatsResponseDtoResponseBandwidthCurrentYear",
    "GetBandwidthStatsResponseDtoResponseBandwidthLast30Days",
    "GetBandwidthStatsResponseDtoResponseBandwidthLastSevenDays",
    "GetBandwidthStatsResponseDtoResponseBandwidthLastTwoDays",
    "GetConfigProfileByUuidResponseDto",
    "GetConfigProfileByUuidResponseDtoResponse",
    "GetConfigProfileByUuidResponseDtoResponseInboundsItem",
    "GetConfigProfileByUuidResponseDtoResponseNodesItem",
    "GetConfigProfilesResponseDto",
    "GetConfigProfilesResponseDtoResponse",
    "GetConfigProfilesResponseDtoResponseConfigProfilesItem",
    "GetConfigProfilesResponseDtoResponseConfigProfilesItemInboundsItem",
    "GetConfigProfilesResponseDtoResponseConfigProfilesItemNodesItem",
    "GetInboundsByProfileUuidResponseDto",
    "GetInboundsByProfileUuidResponseDtoResponse",
    "GetInboundsByProfileUuidResponseDtoResponseInboundsItem",
    "GetInfraBillingHistoryRecordsResponseDto",
    "GetInfraBillingHistoryRecordsResponseDtoResponse",
    "GetInfraBillingHistoryRecordsResponseDtoResponseRecordsItem",
    "GetInfraBillingHistoryRecordsResponseDtoResponseRecordsItemProvider",
    "GetInfraBillingNodesResponseDto",
    "GetInfraBillingNodesResponseDtoResponse",
    "GetInfraBillingNodesResponseDtoResponseAvailableBillingNodesItem",
    "GetInfraBillingNodesResponseDtoResponseBillingNodesItem",
    "GetInfraBillingNodesResponseDtoResponseBillingNodesItemNode",
    "GetInfraBillingNodesResponseDtoResponseBillingNodesItemProvider",
    "GetInfraBillingNodesResponseDtoResponseStats",
    "GetInfraProviderByUuidResponseDto",
    "GetInfraProviderByUuidResponseDtoResponse",
    "GetInfraProviderByUuidResponseDtoResponseBillingHistory",
    "GetInfraProviderByUuidResponseDtoResponseBillingNodesItem",
    "GetInfraProvidersResponseDto",
    "GetInfraProvidersResponseDtoResponse",
    "GetInfraProvidersResponseDtoResponseProvidersItem",
    "GetInfraProvidersResponseDtoResponseProvidersItemBillingHistory",
    "GetInfraProvidersResponseDtoResponseProvidersItemBillingNodesItem",
    "GetInternalSquadAccessibleNodesResponseDto",
    "GetInternalSquadAccessibleNodesResponseDtoResponse",
    "GetInternalSquadAccessibleNodesResponseDtoResponseAccessibleNodesItem",
    "GetInternalSquadByUuidResponseDto",
    "GetInternalSquadByUuidResponseDtoResponse",
    "GetInternalSquadByUuidResponseDtoResponseInboundsItem",
    "GetInternalSquadByUuidResponseDtoResponseInfo",
    "GetInternalSquadsResponseDto",
    "GetInternalSquadsResponseDtoResponse",
    "GetInternalSquadsResponseDtoResponseInternalSquadsItem",
    "GetInternalSquadsResponseDtoResponseInternalSquadsItemInboundsItem",
    "GetInternalSquadsResponseDtoResponseInternalSquadsItemInfo",
    "GetNodesMetricsResponseDto",
    "GetNodesMetricsResponseDtoResponse",
    "GetNodesMetricsResponseDtoResponseNodesItem",
    "GetNodesMetricsResponseDtoResponseNodesItemInboundsStatsItem",
    "GetNodesMetricsResponseDtoResponseNodesItemOutboundsStatsItem",
    "GetNodesRealtimeUsageResponseDto",
    "GetNodesRealtimeUsageResponseDtoResponseItem",
    "GetNodesStatisticsResponseDto",
    "GetNodesStatisticsResponseDtoResponse",
    "GetNodesStatisticsResponseDtoResponseLastSevenDaysItem",
    "GetNodesUsageByRangeResponseDto",
    "GetNodesUsageByRangeResponseDtoResponseItem",
    "GetNodeUserUsageByRangeResponseDto",
    "GetNodeUserUsageByRangeResponseDtoResponseItem",
    "GetOneHostResponseDto",
    "GetOneHostResponseDtoResponse",
    "GetOneHostResponseDtoResponseInbound",
    "GetOneHostResponseDtoResponseSecurityLayer",
    "GetOneNodeResponseDto",
    "GetOneNodeResponseDtoResponse",
    "GetOneNodeResponseDtoResponseConfigProfile",
    "GetOneNodeResponseDtoResponseConfigProfileActiveInboundsItem",
    "GetOneNodeResponseDtoResponseProviderType0",
    "GetPubKeyResponseDto",
    "GetPubKeyResponseDtoResponse",
    "GetRawSubscriptionByShortUuidResponseDto",
    "GetRawSubscriptionByShortUuidResponseDtoResponse",
    "GetRawSubscriptionByShortUuidResponseDtoResponseHeaders",
    "GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItem",
    "GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemAdditionalParamsType0",
    "GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemDbData",
    "GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemDbDataRawInboundType0",
    "GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemMuxParamsType0",
    "GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemProtocolOptionsType0",
    "GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemProtocolOptionsType0SsType0",
    "GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemSockoptParamsType0",
    "GetRawSubscriptionByShortUuidResponseDtoResponseRawHostsItemXHttpExtraParamsType0",
    "GetRawSubscriptionByShortUuidResponseDtoResponseUser",
    "GetRawSubscriptionByShortUuidResponseDtoResponseUserTrafficLimitStrategy",
    "GetRawSubscriptionByShortUuidResponseDtoResponseUserUserStatus",
    "GetRemnawaveHealthResponseDto",
    "GetRemnawaveHealthResponseDtoResponse",
    "GetRemnawaveHealthResponseDtoResponsePm2StatsItem",
    "GetStatsResponseDto",
    "GetStatsResponseDtoResponse",
    "GetStatsResponseDtoResponseCpu",
    "GetStatsResponseDtoResponseMemory",
    "GetStatsResponseDtoResponseNodes",
    "GetStatsResponseDtoResponseOnlineStats",
    "GetStatsResponseDtoResponseUsers",
    "GetStatsResponseDtoResponseUsersStatusCounts",
    "GetStatusResponseDto",
    "GetStatusResponseDtoResponse",
    "GetStatusResponseDtoResponseOauth2",
    "GetStatusResponseDtoResponseOauth2Providers",
    "GetStatusResponseDtoResponseTgAuthType0",
    "GetSubscriptionByUsernameResponseDto",
    "GetSubscriptionByUsernameResponseDtoResponse",
    "GetSubscriptionByUsernameResponseDtoResponseSsConfLinks",
    "GetSubscriptionByUsernameResponseDtoResponseUser",
    "GetSubscriptionByUsernameResponseDtoResponseUserTrafficLimitStrategy",
    "GetSubscriptionByUsernameResponseDtoResponseUserUserStatus",
    "GetSubscriptionInfoResponseDto",
    "GetSubscriptionInfoResponseDtoResponse",
    "GetSubscriptionInfoResponseDtoResponseHapp",
    "GetSubscriptionInfoResponseDtoResponseSsConfLinks",
    "GetSubscriptionInfoResponseDtoResponseUser",
    "GetSubscriptionInfoResponseDtoResponseUserTrafficLimitStrategy",
    "GetSubscriptionInfoResponseDtoResponseUserUserStatus",
    "GetSubscriptionSettingsResponseDto",
    "GetSubscriptionSettingsResponseDtoResponse",
    "GetSubscriptionSettingsResponseDtoResponseCustomResponseHeadersType0",
    "GetTemplateResponseDto",
    "GetTemplateResponseDtoResponse",
    "GetTemplateResponseDtoResponseTemplateType",
    "GetUserAccessibleNodesResponseDto",
    "GetUserAccessibleNodesResponseDtoResponse",
    "GetUserAccessibleNodesResponseDtoResponseActiveNodesItem",
    "GetUserAccessibleNodesResponseDtoResponseActiveNodesItemActiveSquadsItem",
    "GetUserByEmailResponseDto",
    "GetUserByEmailResponseDtoResponseItem",
    "GetUserByEmailResponseDtoResponseItemActiveInternalSquadsItem",
    "GetUserByEmailResponseDtoResponseItemHapp",
    "GetUserByEmailResponseDtoResponseItemLastConnectedNodeType0",
    "GetUserByEmailResponseDtoResponseItemStatus",
    "GetUserByEmailResponseDtoResponseItemTrafficLimitStrategy",
    "GetUserByShortUuidResponseDto",
    "GetUserByShortUuidResponseDtoResponse",
    "GetUserByShortUuidResponseDtoResponseActiveInternalSquadsItem",
    "GetUserByShortUuidResponseDtoResponseHapp",
    "GetUserByShortUuidResponseDtoResponseLastConnectedNodeType0",
    "GetUserByShortUuidResponseDtoResponseStatus",
    "GetUserByShortUuidResponseDtoResponseTrafficLimitStrategy",
    "GetUserByTagResponseDto",
    "GetUserByTagResponseDtoResponseItem",
    "GetUserByTagResponseDtoResponseItemActiveInternalSquadsItem",
    "GetUserByTagResponseDtoResponseItemHapp",
    "GetUserByTagResponseDtoResponseItemLastConnectedNodeType0",
    "GetUserByTagResponseDtoResponseItemStatus",
    "GetUserByTagResponseDtoResponseItemTrafficLimitStrategy",
    "GetUserByTelegramIdResponseDto",
    "GetUserByTelegramIdResponseDtoResponseItem",
    "GetUserByTelegramIdResponseDtoResponseItemActiveInternalSquadsItem",
    "GetUserByTelegramIdResponseDtoResponseItemHapp",
    "GetUserByTelegramIdResponseDtoResponseItemLastConnectedNodeType0",
    "GetUserByTelegramIdResponseDtoResponseItemStatus",
    "GetUserByTelegramIdResponseDtoResponseItemTrafficLimitStrategy",
    "GetUserByUsernameResponseDto",
    "GetUserByUsernameResponseDtoResponse",
    "GetUserByUsernameResponseDtoResponseActiveInternalSquadsItem",
    "GetUserByUsernameResponseDtoResponseHapp",
    "GetUserByUsernameResponseDtoResponseLastConnectedNodeType0",
    "GetUserByUsernameResponseDtoResponseStatus",
    "GetUserByUsernameResponseDtoResponseTrafficLimitStrategy",
    "GetUserByUuidResponseDto",
    "GetUserByUuidResponseDtoResponse",
    "GetUserByUuidResponseDtoResponseActiveInternalSquadsItem",
    "GetUserByUuidResponseDtoResponseHapp",
    "GetUserByUuidResponseDtoResponseLastConnectedNodeType0",
    "GetUserByUuidResponseDtoResponseStatus",
    "GetUserByUuidResponseDtoResponseTrafficLimitStrategy",
    "GetUserHwidDevicesResponseDto",
    "GetUserHwidDevicesResponseDtoResponse",
    "GetUserHwidDevicesResponseDtoResponseDevicesItem",
    "GetUserUsageByRangeResponseDto",
    "GetUserUsageByRangeResponseDtoResponseItem",
    "HostsBulkActionsControllerDeleteHostsResponse500",
    "HostsBulkActionsControllerDisableHostsResponse500",
    "HostsBulkActionsControllerEnableHostsResponse500",
    "HostsBulkActionsControllerSetInboundToHostsResponse500",
    "HostsBulkActionsControllerSetPortToHostsResponse500",
    "HostsControllerCreateHostResponse500",
    "HostsControllerDeleteHostResponse500",
    "HostsControllerGetAllHostsResponse500",
    "HostsControllerGetAllHostTagsResponse500",
    "HostsControllerGetOneHostResponse500",
    "HostsControllerReorderHostsResponse500",
    "HostsControllerUpdateHostResponse500",
    "HwidUserDevicesControllerCreateUserHwidDeviceResponse500",
    "HwidUserDevicesControllerDeleteUserHwidDeviceResponse500",
    "HwidUserDevicesControllerGetUserHwidDevicesResponse500",
    "InfraBillingControllerCreateInfraBillingHistoryRecordResponse500",
    "InfraBillingControllerCreateInfraBillingNodeResponse500",
    "InfraBillingControllerCreateInfraProviderResponse500",
    "InfraBillingControllerDeleteInfraBillingHistoryRecordByUuidResponse500",
    "InfraBillingControllerDeleteInfraBillingNodeByUuidResponse500",
    "InfraBillingControllerDeleteInfraProviderByUuidResponse500",
    "InfraBillingControllerGetBillingNodesResponse500",
    "InfraBillingControllerGetInfraBillingHistoryRecordsResponse500",
    "InfraBillingControllerGetInfraProviderByUuidResponse500",
    "InfraBillingControllerGetInfraProvidersResponse500",
    "InfraBillingControllerUpdateInfraBillingNodeResponse500",
    "InfraBillingControllerUpdateInfraProviderResponse500",
    "InternalSquadControllerAddUsersToInternalSquadResponse500",
    "InternalSquadControllerCreateInternalSquadResponse500",
    "InternalSquadControllerDeleteInternalSquadResponse500",
    "InternalSquadControllerGetInternalSquadAccessibleNodesResponse500",
    "InternalSquadControllerGetInternalSquadByUuidResponse500",
    "InternalSquadControllerGetInternalSquadsResponse500",
    "InternalSquadControllerRemoveUsersFromInternalSquadResponse500",
    "InternalSquadControllerUpdateInternalSquadResponse500",
    "KeygenControllerGenerateKeyResponse500",
    "LoginRequestDto",
    "LoginResponseDto",
    "LoginResponseDtoResponse",
    "NodesControllerCreateNodeResponse500",
    "NodesControllerDeleteNodeResponse500",
    "NodesControllerDisableNodeResponse500",
    "NodesControllerEnableNodeResponse500",
    "NodesControllerGetAllNodesResponse500",
    "NodesControllerGetOneNodeResponse500",
    "NodesControllerReorderNodesResponse500",
    "NodesControllerRestartAllNodesResponse500",
    "NodesControllerRestartNodeResponse500",
    "NodesControllerUpdateNodeResponse500",
    "NodesUsageHistoryControllerGetNodesUsageByRangeResponse500",
    "NodesUserUsageHistoryControllerGetNodesRealtimeUsageResponse500",
    "NodesUserUsageHistoryControllerGetNodeUserUsageResponse500",
    "OAuth2AuthorizeRequestDto",
    "OAuth2AuthorizeRequestDtoProvider",
    "OAuth2AuthorizeResponseDto",
    "OAuth2AuthorizeResponseDtoResponse",
    "OAuth2CallbackRequestDto",
    "OAuth2CallbackRequestDtoProvider",
    "OAuth2CallbackResponseDto",
    "OAuth2CallbackResponseDtoResponse",
    "RegisterRequestDto",
    "RegisterResponseDto",
    "RegisterResponseDtoResponse",
    "RemoveUsersFromInternalSquadResponseDto",
    "RemoveUsersFromInternalSquadResponseDtoResponse",
    "ReorderHostRequestDto",
    "ReorderHostRequestDtoHostsItem",
    "ReorderHostResponseDto",
    "ReorderHostResponseDtoResponse",
    "ReorderNodeRequestDto",
    "ReorderNodeRequestDtoNodesItem",
    "ReorderNodeResponseDto",
    "ReorderNodeResponseDtoResponseItem",
    "ReorderNodeResponseDtoResponseItemConfigProfile",
    "ReorderNodeResponseDtoResponseItemConfigProfileActiveInboundsItem",
    "ReorderNodeResponseDtoResponseItemProviderType0",
    "ResetUserTrafficResponseDto",
    "ResetUserTrafficResponseDtoResponse",
    "ResetUserTrafficResponseDtoResponseActiveInternalSquadsItem",
    "ResetUserTrafficResponseDtoResponseHapp",
    "ResetUserTrafficResponseDtoResponseLastConnectedNodeType0",
    "ResetUserTrafficResponseDtoResponseStatus",
    "ResetUserTrafficResponseDtoResponseTrafficLimitStrategy",
    "RestartAllNodesResponseDto",
    "RestartAllNodesResponseDtoResponse",
    "RestartNodeResponseDto",
    "RestartNodeResponseDtoResponse",
    "RevokeUserSubscriptionBodyDto",
    "RevokeUserSubscriptionResponseDto",
    "RevokeUserSubscriptionResponseDtoResponse",
    "RevokeUserSubscriptionResponseDtoResponseActiveInternalSquadsItem",
    "RevokeUserSubscriptionResponseDtoResponseHapp",
    "RevokeUserSubscriptionResponseDtoResponseLastConnectedNodeType0",
    "RevokeUserSubscriptionResponseDtoResponseStatus",
    "RevokeUserSubscriptionResponseDtoResponseTrafficLimitStrategy",
    "SetInboundToManyHostsRequestDto",
    "SetInboundToManyHostsResponseDto",
    "SetInboundToManyHostsResponseDtoResponseItem",
    "SetInboundToManyHostsResponseDtoResponseItemInbound",
    "SetInboundToManyHostsResponseDtoResponseItemSecurityLayer",
    "SetPortToManyHostsRequestDto",
    "SetPortToManyHostsResponseDto",
    "SetPortToManyHostsResponseDtoResponseItem",
    "SetPortToManyHostsResponseDtoResponseItemInbound",
    "SetPortToManyHostsResponseDtoResponseItemSecurityLayer",
    "SubscriptionControllerGetRawSubscriptionByShortUuidResponse500",
    "SubscriptionControllerGetSubscriptionByClientTypeClientType",
    "SubscriptionControllerGetSubscriptionInfoByShortUuidResponse500",
    "SubscriptionsControllerGetAllSubscriptionsResponse500",
    "SubscriptionsControllerGetSubscriptionByUsernameResponse404",
    "SubscriptionsControllerGetSubscriptionByUsernameResponse500",
    "SubscriptionSettingsControllerGetSettingsResponse500",
    "SubscriptionSettingsControllerUpdateSettingsResponse500",
    "SubscriptionTemplateControllerGetTemplateResponse500",
    "SubscriptionTemplateControllerGetTemplateTemplateType",
    "SubscriptionTemplateControllerUpdateTemplateResponse500",
    "SystemControllerGetBandwidthStatsResponse500",
    "SystemControllerGetNodesMetricsResponse500",
    "SystemControllerGetNodesStatisticsResponse500",
    "SystemControllerGetRemnawaveHealthResponse500",
    "SystemControllerGetStatsResponse500",
    "TelegramCallbackRequestDto",
    "TelegramCallbackResponseDto",
    "TelegramCallbackResponseDtoResponse",
    "UpdateConfigProfileRequestDto",
    "UpdateConfigProfileRequestDtoConfig",
    "UpdateConfigProfileResponseDto",
    "UpdateConfigProfileResponseDtoResponse",
    "UpdateConfigProfileResponseDtoResponseInboundsItem",
    "UpdateConfigProfileResponseDtoResponseNodesItem",
    "UpdateHostRequestDto",
    "UpdateHostRequestDtoAlpn",
    "UpdateHostRequestDtoFingerprint",
    "UpdateHostRequestDtoInbound",
    "UpdateHostRequestDtoSecurityLayer",
    "UpdateHostResponseDto",
    "UpdateHostResponseDtoResponse",
    "UpdateHostResponseDtoResponseInbound",
    "UpdateHostResponseDtoResponseSecurityLayer",
    "UpdateInfraBillingNodeRequestDto",
    "UpdateInfraBillingNodeResponseDto",
    "UpdateInfraBillingNodeResponseDtoResponse",
    "UpdateInfraBillingNodeResponseDtoResponseAvailableBillingNodesItem",
    "UpdateInfraBillingNodeResponseDtoResponseBillingNodesItem",
    "UpdateInfraBillingNodeResponseDtoResponseBillingNodesItemNode",
    "UpdateInfraBillingNodeResponseDtoResponseBillingNodesItemProvider",
    "UpdateInfraBillingNodeResponseDtoResponseStats",
    "UpdateInfraProviderRequestDto",
    "UpdateInfraProviderResponseDto",
    "UpdateInfraProviderResponseDtoResponse",
    "UpdateInfraProviderResponseDtoResponseBillingHistory",
    "UpdateInfraProviderResponseDtoResponseBillingNodesItem",
    "UpdateInternalSquadRequestDto",
    "UpdateInternalSquadResponseDto",
    "UpdateInternalSquadResponseDtoResponse",
    "UpdateInternalSquadResponseDtoResponseInboundsItem",
    "UpdateInternalSquadResponseDtoResponseInfo",
    "UpdateNodeRequestDto",
    "UpdateNodeRequestDtoConfigProfile",
    "UpdateNodeResponseDto",
    "UpdateNodeResponseDtoResponse",
    "UpdateNodeResponseDtoResponseConfigProfile",
    "UpdateNodeResponseDtoResponseConfigProfileActiveInboundsItem",
    "UpdateNodeResponseDtoResponseProviderType0",
    "UpdateSubscriptionSettingsRequestDto",
    "UpdateSubscriptionSettingsRequestDtoCustomResponseHeaders",
    "UpdateSubscriptionSettingsResponseDto",
    "UpdateSubscriptionSettingsResponseDtoResponse",
    "UpdateSubscriptionSettingsResponseDtoResponseCustomResponseHeadersType0",
    "UpdateTemplateRequestDto",
    "UpdateTemplateRequestDtoTemplateJson",
    "UpdateTemplateRequestDtoTemplateType",
    "UpdateTemplateResponseDto",
    "UpdateTemplateResponseDtoResponse",
    "UpdateTemplateResponseDtoResponseTemplateType",
    "UpdateUserRequestDto",
    "UpdateUserRequestDtoStatus",
    "UpdateUserRequestDtoTrafficLimitStrategy",
    "UpdateUserResponseDto",
    "UpdateUserResponseDtoResponse",
    "UpdateUserResponseDtoResponseActiveInternalSquadsItem",
    "UpdateUserResponseDtoResponseHapp",
    "UpdateUserResponseDtoResponseLastConnectedNodeType0",
    "UpdateUserResponseDtoResponseStatus",
    "UpdateUserResponseDtoResponseTrafficLimitStrategy",
    "UsersBulkActionsControllerBulkAllResetUserTrafficResponse500",
    "UsersBulkActionsControllerBulkDeleteUsersByStatusResponse500",
    "UsersBulkActionsControllerBulkDeleteUsersResponse500",
    "UsersBulkActionsControllerBulkResetUserTrafficResponse500",
    "UsersBulkActionsControllerBulkRevokeUsersSubscriptionResponse500",
    "UsersBulkActionsControllerBulkUpdateAllUsersResponse500",
    "UsersBulkActionsControllerBulkUpdateUsersInternalSquadsResponse500",
    "UsersBulkActionsControllerBulkUpdateUsersResponse500",
    "UsersControllerCreateUserResponse500",
    "UsersControllerDeleteUserResponse500",
    "UsersControllerDisableUserResponse500",
    "UsersControllerEnableUserResponse500",
    "UsersControllerGetAllTagsResponse500",
    "UsersControllerGetAllUsersResponse500",
    "UsersControllerGetUserAccessibleNodesResponse500",
    "UsersControllerGetUserByShortUuidResponse500",
    "UsersControllerGetUserByTelegramIdResponse500",
    "UsersControllerGetUserByUsernameResponse500",
    "UsersControllerGetUserByUuidResponse500",
    "UsersControllerGetUsersByEmailResponse500",
    "UsersControllerGetUsersByTagResponse500",
    "UsersControllerResetUserTrafficResponse500",
    "UsersControllerRevokeUserSubscriptionResponse500",
    "UsersControllerUpdateUserResponse500",
    "UsersStatsControllerGetUserUsageByRangeResponse500",
)
