from collections.abc import Mapping
from typing import Any, TypeVar, Union

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="RevokeUserSubscriptionBodyDto")


@_attrs_define
class RevokeUserSubscriptionBodyDto:
    """
    Attributes:
        short_uuid (Union[Unset, str]): Optional. If not provided, a new short UUID will be generated by Remnawave.
            Please note that it is strongly recommended to allow Remnawave to generate the short UUID.
    """

    short_uuid: Union[Unset, str] = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        short_uuid = self.short_uuid

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if short_uuid is not UNSET:
            field_dict["shortUuid"] = short_uuid

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        short_uuid = d.pop("shortUuid", UNSET)

        revoke_user_subscription_body_dto = cls(
            short_uuid=short_uuid,
        )

        revoke_user_subscription_body_dto.additional_properties = d
        return revoke_user_subscription_body_dto

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
